#### Q1 ####

In [1]:
import requests
import bs4

In [2]:
from selenium import webdriver
from selenium.webdriver.support.select import Select

In [3]:
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait

In [4]:
import pandas as pd

In [5]:
import random
import time

In [6]:
driver = webdriver.Firefox(executable_path=r'/Users/richard/Downloads/geckodriver 2')

In [7]:
#driver.close()

In [7]:
driver.get('http://www.mlb.com')

In [9]:
time.sleep(5)
stats_header_bar = driver.find_element_by_class_name('megamenu-navbar-overflow__menu-item--stats')

In [10]:
stats_header_bar.click()

In [11]:
time.sleep(5)
stats_line_items = stats_header_bar.find_elements_by_tag_name('li')

In [12]:
stats_line_items[0].click()

In [13]:
time.sleep(5)
hitting_season_element = driver.find_element_by_id('sp_hitting_season')
season_select = Select(hitting_season_element)

In [14]:
season_select.select_by_index(3)

In [15]:
time.sleep(5)
team_2015 = driver.find_element_by_css_selector("#st_parent")

In [16]:
team_2015.click()

In [17]:
time.sleep(5)
regular_season_element = driver.find_element_by_id('st_hitting_game_type')
regular_season_select = Select(regular_season_element)

In [18]:
regular_season_select.select_by_visible_text('Regular Season')

In [19]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')

In [20]:
soup = bs4.BeautifulSoup(data_html,"html5lib")

In [21]:
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [22]:
len(head)

32

In [23]:
df1=pd.DataFrame(columns = head)

In [24]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)

In [25]:
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [26]:
for i in range(30):
    df1.loc[i]= context_b[i]

In [27]:
df1 = df1.drop("",axis=1)

In [28]:
df1

,RK,Team,League,G,AB,R,H,2B,3B,HR,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,Detroit Tigers,AL,161,5605,689,1515,289,49,151,...,23,35,2355,489,152,1584,1460,1.08,23702,6159
1,2,Toronto Blue Jays,AL,162,5509,891,1480,308,17,232,...,36,62,2518,557,140,1724,1395,1.24,24051,6231
2,3,Kansas City Royals,AL,162,5575,724,1497,300,42,139,...,34,47,2298,481,133,1759,1560,1.13,22705,6116
3,4,San Francisco Giants,NL,162,5565,696,1486,288,39,136,...,45,37,2260,463,142,1830,1314,1.39,23191,6153
4,5,Colorado Rockies,NL,162,5572,737,1479,274,49,186,...,44,34,2409,509,114,1628,1374,1.18,22661,6071
5,6,Boston Red Sox,AL,162,5640,748,1495,294,33,161,...,30,42,2338,488,127,1756,1440,1.22,24709,6237
6,7,Arizona Diamondbacks,NL,162,5649,720,1494,289,48,154,...,46,57,2341,491,134,1759,1321,1.33,23332,6276
7,8,Miami Marlins,NL,162,5463,613,1420,236,40,120,...,71,40,2096,396,133,1921,1216,1.58,22254,5988
8,9,Pittsburgh Pirates,NL,162,5631,697,1462,292,27,140,...,63,41,2228,459,115,1739,1327,1.31,23889,6285
9,10,Texas Rangers,AL,162,5511,751,1419,279,32,172,...,43,54,2278,483,99,1648,1407,1.17,23738,6187
10,11,Cleveland Indians,AL,161,5439,669,1395,303,29,141,...,47,50,2179,473,134,1675,1443,1.16,23795,6109
11,12,St. Louis Cardinals,NL,162,5484,647,1386,288,39,137,...,39,42,2163,464,128,1677,1363,1.23,23494,6139
12,13,Tampa Bay Rays,AL,162,5485,644,1383,278,32,167,...,19,47,2226,477,121,1510,1469,1.03,23210,6071
13,14,Milwaukee Brewers,NL,162,5480,655,1378,274,34,145,...,55,34,2155,453,130,1730,1292,1.34,22558,6024
14,15,Atlanta Braves,NL,162,5420,573,1361,251,18,100,...,67,31,1948,369,148,1902,1296,1.47,22644,6034
15,16,Washington Nationals,NL,162,5428,703,1363,265,13,177,...,55,51,2185,455,129,1704,1252,1.36,23247,6117
16,17,New York Yankees,AL,162,5567,764,1397,272,19,212,...,24,54,2343,503,105,1558,1568,0.99,24523,6268
17,18,Oakland Athletics,AL,162,5600,694,1405,277,46,146,...,14,38,2212,469,124,1704,1548,1.10,23808,6171
18,19,Los Angeles Dodgers,NL,162,5385,667,1346,263,26,187,...,49,30,2222,476,135,1630,1365,1.19,23602,6090
19,20,Baltimore Orioles,AL,162,5485,713,1370,246,20,217,...,20,32,2307,483,127,1561,1402,1.11,22911,6007
20,21,Houston Astros,AL,162,5459,729,1363,278,26,230,...,28,43,2383,534,102,1439,1438,1.00,23543,6073
21,22,Chicago White Sox,AL,162,5533,622,1381,260,27,136,...,30,37,2103,423,125,1807,1306,1.38,23140,6070
22,23,Seattle Mariners,AL,162,5544,656,1379,262,22,198,...,38,35,2279,482,123,1607,1418,1.13,23814,6131
23,24,Philadelphia Phillies,NL,162,5529,626,1374,272,37,130,...,53,29,2110,439,119,1693,1389,1.22,22644,6053
24,25,Cincinnati Reds,NL,162,5571,640,1382,257,27,167,...,47,40,2194,451,112,1640,1493,1.10,23533,6196
25,26,Minnesota Twins,AL,162,5467,696,1349,277,44,156,...,30,41,2182,477,133,1634,1424,1.15,23100,6017
26,27,Los Angeles Angels,AL,162,5417,661,1331,243,21,176,...,37,40,2144,440,116,1676,1453,1.15,22727,5990
27,28,New York Mets,NL,162,5527,683,1351,295,17,177,...,29,32,2211,489,130,1540,1537,1.00,23931,6145
28,29,Chicago Cubs,NL,162,5491,689,1341,272,30,171,...,32,35,2186,473,101,1462,1338,1.09,24646,6200
29,30,San Diego Padres,NL,162,5457,650,1324,260,36,148,...,52,42,2100,444,108,1597,1411,1.13,23200,6019

#### Q2 ####

In [29]:
time.sleep(5)
AL_bar = driver.find_element_by_css_selector("#st_hitting-0 > fieldset:nth-child(2) > label:nth-child(4)")

In [30]:
AL_bar.click()

In [31]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')

In [32]:
soup = bs4.BeautifulSoup(data_html,"html5lib")

In [33]:
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [34]:
df2=pd.DataFrame(columns = head)

In [35]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)

In [36]:
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [37]:
for i in range(15):
    df2.loc[i]= context_b[i]
df2

,RK,Team,,League,G,AB,R,H,2B,3B,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,Detroit Tigers,det,AL,161,5605,689,1515,289,49,...,23,35,2355,489,152,1584,1460,1.08,23702,6159
1,2,Toronto Blue Jays,tor,AL,162,5509,891,1480,308,17,...,36,62,2518,557,140,1724,1395,1.24,24051,6231
2,3,Kansas City Royals,kc,AL,162,5575,724,1497,300,42,...,34,47,2298,481,133,1759,1560,1.13,22705,6116
3,4,Boston Red Sox,bos,AL,162,5640,748,1495,294,33,...,30,42,2338,488,127,1756,1440,1.22,24709,6237
4,5,Texas Rangers,tex,AL,162,5511,751,1419,279,32,...,43,54,2278,483,99,1648,1407,1.17,23738,6187
5,6,Cleveland Indians,cle,AL,161,5439,669,1395,303,29,...,47,50,2179,473,134,1675,1443,1.16,23795,6109
6,7,Tampa Bay Rays,tb,AL,162,5485,644,1383,278,32,...,19,47,2226,477,121,1510,1469,1.03,23210,6071
7,8,New York Yankees,nyy,AL,162,5567,764,1397,272,19,...,24,54,2343,503,105,1558,1568,0.99,24523,6268
8,9,Oakland Athletics,oak,AL,162,5600,694,1405,277,46,...,14,38,2212,469,124,1704,1548,1.10,23808,6171
9,10,Baltimore Orioles,bal,AL,162,5485,713,1370,246,20,...,20,32,2307,483,127,1561,1402,1.11,22911,6007
10,11,Houston Astros,hou,AL,162,5459,729,1363,278,26,...,28,43,2383,534,102,1439,1438,1.00,23543,6073
11,12,Chicago White Sox,cws,AL,162,5533,622,1381,260,27,...,30,37,2103,423,125,1807,1306,1.38,23140,6070
12,13,Seattle Mariners,sea,AL,162,5544,656,1379,262,22,...,38,35,2279,482,123,1607,1418,1.13,23814,6131
13,14,Minnesota Twins,min,AL,162,5467,696,1349,277,44,...,30,41,2182,477,133,1634,1424,1.15,23100,6017
14,15,Los Angeles Angels,ana,AL,162,5417,661,1331,243,21,...,37,40,2144,440,116,1676,1453,1.15,22727,5990

In [38]:
df2 = df2.drop("",axis=1)

In [39]:
df2

,RK,Team,League,G,AB,R,H,2B,3B,HR,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,Detroit Tigers,AL,161,5605,689,1515,289,49,151,...,23,35,2355,489,152,1584,1460,1.08,23702,6159
1,2,Toronto Blue Jays,AL,162,5509,891,1480,308,17,232,...,36,62,2518,557,140,1724,1395,1.24,24051,6231
2,3,Kansas City Royals,AL,162,5575,724,1497,300,42,139,...,34,47,2298,481,133,1759,1560,1.13,22705,6116
3,4,Boston Red Sox,AL,162,5640,748,1495,294,33,161,...,30,42,2338,488,127,1756,1440,1.22,24709,6237
4,5,Texas Rangers,AL,162,5511,751,1419,279,32,172,...,43,54,2278,483,99,1648,1407,1.17,23738,6187
5,6,Cleveland Indians,AL,161,5439,669,1395,303,29,141,...,47,50,2179,473,134,1675,1443,1.16,23795,6109
6,7,Tampa Bay Rays,AL,162,5485,644,1383,278,32,167,...,19,47,2226,477,121,1510,1469,1.03,23210,6071
7,8,New York Yankees,AL,162,5567,764,1397,272,19,212,...,24,54,2343,503,105,1558,1568,0.99,24523,6268
8,9,Oakland Athletics,AL,162,5600,694,1405,277,46,146,...,14,38,2212,469,124,1704,1548,1.10,23808,6171
9,10,Baltimore Orioles,AL,162,5485,713,1370,246,20,217,...,20,32,2307,483,127,1561,1402,1.11,22911,6007
10,11,Houston Astros,AL,162,5459,729,1363,278,26,230,...,28,43,2383,534,102,1439,1438,1.00,23543,6073
11,12,Chicago White Sox,AL,162,5533,622,1381,260,27,136,...,30,37,2103,423,125,1807,1306,1.38,23140,6070
12,13,Seattle Mariners,AL,162,5544,656,1379,262,22,198,...,38,35,2279,482,123,1607,1418,1.13,23814,6131
13,14,Minnesota Twins,AL,162,5467,696,1349,277,44,156,...,30,41,2182,477,133,1634,1424,1.15,23100,6017
14,15,Los Angeles Angels,AL,162,5417,661,1331,243,21,176,...,37,40,2144,440,116,1676,1453,1.15,22727,5990

In [40]:
time.sleep(5)
NL_bar = driver.find_element_by_css_selector("#st_hitting-0 > fieldset:nth-child(2) > label:nth-child(6)")

In [41]:
NL_bar.click()

In [42]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')

In [43]:
soup = bs4.BeautifulSoup(data_html,"html5lib")

In [44]:
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [45]:
df3=pd.DataFrame(columns = head)

In [46]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)

In [47]:
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [48]:
for i in range(15):
    df3.loc[i]= context_b[i]

In [49]:
df3.drop("", axis=1)

,RK,Team,League,G,AB,R,H,2B,3B,HR,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,San Francisco Giants,NL,162,5565,696,1486,288,39,136,...,45,37,2260,463,142,1830,1314,1.39,23191,6153
1,2,Colorado Rockies,NL,162,5572,737,1479,274,49,186,...,44,34,2409,509,114,1628,1374,1.18,22661,6071
2,3,Arizona Diamondbacks,NL,162,5649,720,1494,289,48,154,...,46,57,2341,491,134,1759,1321,1.33,23332,6276
3,4,Miami Marlins,NL,162,5463,613,1420,236,40,120,...,71,40,2096,396,133,1921,1216,1.58,22254,5988
4,5,Pittsburgh Pirates,NL,162,5631,697,1462,292,27,140,...,63,41,2228,459,115,1739,1327,1.31,23889,6285
5,6,St. Louis Cardinals,NL,162,5484,647,1386,288,39,137,...,39,42,2163,464,128,1677,1363,1.23,23494,6139
6,7,Milwaukee Brewers,NL,162,5480,655,1378,274,34,145,...,55,34,2155,453,130,1730,1292,1.34,22558,6024
7,8,Atlanta Braves,NL,162,5420,573,1361,251,18,100,...,67,31,1948,369,148,1902,1296,1.47,22644,6034
8,9,Washington Nationals,NL,162,5428,703,1363,265,13,177,...,55,51,2185,455,129,1704,1252,1.36,23247,6117
9,10,Los Angeles Dodgers,NL,162,5385,667,1346,263,26,187,...,49,30,2222,476,135,1630,1365,1.19,23602,6090
10,11,Philadelphia Phillies,NL,162,5529,626,1374,272,37,130,...,53,29,2110,439,119,1693,1389,1.22,22644,6053
11,12,Cincinnati Reds,NL,162,5571,640,1382,257,27,167,...,47,40,2194,451,112,1640,1493,1.10,23533,6196
12,13,New York Mets,NL,162,5527,683,1351,295,17,177,...,29,32,2211,489,130,1540,1537,1.00,23931,6145
13,14,Chicago Cubs,NL,162,5491,689,1341,272,30,171,...,32,35,2186,473,101,1462,1338,1.09,24646,6200
14,15,San Diego Padres,NL,162,5457,650,1324,260,36,148,...,52,42,2100,444,108,1597,1411,1.13,23200,6019

In [50]:
time.sleep(5)
hitting_hitting_splits_element = driver.find_element_by_id('st_hitting_hitting_splits')
splits_select = Select(hitting_hitting_splits_element)

In [51]:
splits_select.select_by_visible_text('First Inning')

In [52]:
AL_bar.click()

In [53]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')

In [54]:
soup = bs4.BeautifulSoup(data_html,"html5lib")

In [55]:
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [56]:
df4=pd.DataFrame(columns = head)

In [57]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)

In [58]:
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [59]:
for i in range(15):
    df4.loc[i]= context_b[i]

In [60]:
df4.drop("", axis=1)

,RK,Team,League,G,AB,R,H,2B,3B,HR,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,Kansas City Royals,AL,-,665,106,206,44,2,20,...,2,4,314,66,14,189,175,1.08,2578,720
1,2,Detroit Tigers,AL,-,642,102,196,36,5,23,...,1,7,311,64,19,170,173,0.98,2848,709
2,3,Texas Rangers,AL,-,648,120,196,37,7,21,...,6,10,310,65,13,209,142,1.47,2953,753
3,4,New York Yankees,AL,-,647,125,188,37,3,31,...,5,15,324,71,7,149,190,0.78,3007,739
4,5,Seattle Mariners,AL,-,645,91,181,39,0,27,...,0,6,301,66,11,188,145,1.30,2716,696
5,6,Minnesota Twins,AL,-,625,92,166,39,1,27,...,0,7,288,67,15,166,173,0.96,2723,692
6,7,Houston Astros,AL,-,604,82,159,24,3,26,...,5,8,267,53,15,169,166,1.02,2604,678
7,8,Toronto Blue Jays,AL,-,618,108,162,39,2,34,...,1,8,307,75,17,189,157,1.20,2925,708
8,9,Boston Red Sox,AL,-,629,78,164,36,4,16,...,0,2,256,56,14,190,159,1.19,2848,685
9,10,Baltimore Orioles,AL,-,625,93,162,32,2,30,...,1,4,288,64,13,164,160,1.03,2722,696
10,11,Tampa Bay Rays,AL,-,608,76,157,36,3,19,...,0,5,256,58,14,177,162,1.09,2633,670
11,12,Oakland Athletics,AL,-,625,81,161,29,4,17,...,0,4,249,50,17,208,170,1.22,2668,692
12,13,Cleveland Indians,AL,-,607,68,156,35,4,18,...,8,5,253,57,11,179,170,1.05,2806,682
13,14,Chicago White Sox,AL,-,614,71,155,28,4,13,...,2,3,230,45,19,207,158,1.31,2640,671
14,15,Los Angeles Angels,AL,-,618,88,153,25,4,33,...,1,4,285,62,8,169,173,0.98,2567,672

In [61]:
NL_bar.click()

In [62]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')

In [63]:
soup = bs4.BeautifulSoup(data_html,"html5lib")

In [64]:
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [65]:
df5=pd.DataFrame(columns = head)

In [66]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)

In [67]:
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [68]:
for i in range(15):
    df5.loc[i]= context_b[i]

In [69]:
df5.drop("", axis=1)

,RK,Team,League,G,AB,R,H,2B,3B,HR,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,Colorado Rockies,NL,-,659,120,205,39,7,32,...,4,5,354,78,19,194,165,1.18,2752,721
1,2,Arizona Diamondbacks,NL,-,640,84,183,36,5,16,...,0,5,277,57,16,189,161,1.17,2659,708
2,3,Miami Marlins,NL,-,641,88,178,29,2,18,...,0,5,265,49,13,207,140,1.48,2611,689
3,4,Milwaukee Brewers,NL,-,638,102,177,30,7,27,...,4,2,302,64,16,210,132,1.59,2727,695
4,5,San Francisco Giants,NL,-,629,72,171,25,5,15,...,1,9,251,45,16,193,167,1.16,2614,682
5,6,Cincinnati Reds,NL,-,635,96,172,40,4,25,...,0,5,295,69,12,176,171,1.03,2798,709
6,7,Washington Nationals,NL,-,633,89,171,38,1,24,...,3,5,283,63,16,186,149,1.25,2807,703
7,8,Atlanta Braves,NL,-,611,75,164,37,0,12,...,2,8,237,49,20,215,161,1.34,2599,686
8,9,Pittsburgh Pirates,NL,-,634,86,168,34,4,14,...,3,4,252,52,6,173,168,1.03,2732,703
9,10,St. Louis Cardinals,NL,-,616,80,159,40,6,13,...,0,5,250,59,18,177,166,1.07,2714,689
10,11,Los Angeles Dodgers,NL,-,605,72,154,34,6,25,...,1,7,275,65,18,169,149,1.13,2677,678
11,12,New York Mets,NL,-,629,74,156,36,1,24,...,1,1,266,61,10,146,189,0.77,2750,689
12,13,San Diego Padres,NL,-,612,86,151,25,3,21,...,1,9,245,49,12,174,167,1.04,2651,683
13,14,Philadelphia Phillies,NL,-,610,63,149,21,4,8,...,2,6,202,33,16,200,157,1.27,2531,664
14,15,Chicago Cubs,NL,-,596,88,138,26,6,19,...,0,8,233,51,9,167,140,1.19,2860,702

#### Q3 ####

In [70]:
time.sleep(5)
Player_bar = driver.find_element_by_css_selector("#sp_parent")

In [71]:
Player_bar.click()

In [72]:
time.sleep(5)
MLB_bar = driver.find_element_by_css_selector("#sp_hitting-1 > fieldset:nth-child(1) > label:nth-child(2)")

In [73]:
MLB_bar.click()

In [74]:
time.sleep(5)
hitting_hitting_splits_element1 = driver.find_element_by_id('sp_hitting_hitting_splits')
splits_select1 = Select(hitting_hitting_splits_element1)

In [75]:
splits_select1.select_by_index(0)

In [76]:
season_select.select_by_index(1)

In [77]:
time.sleep(5)
Team_element = driver.find_element_by_id('sp_hitting_team_id')
team_select = Select(Team_element)

In [78]:
team_select.select_by_visible_text('New York Yankees')

In [79]:
time.sleep(5)
AB_button=driver.find_element_by_css_selector("th.dg-ab > abbr:nth-child(1)")

In [80]:
AB_button.click()

In [81]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')
soup = bs4.BeautifulSoup(data_html,"html5lib")
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [82]:
df6=pd.DataFrame(columns = head)

In [83]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)
        
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [84]:
for i in range(17):
    df6.loc[i]= context_b[i]

In [85]:
df6.drop("", axis=1)

,RK,Player,Team,â–²,Pos,G,AB,R,H,2B,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Gardner, B",NYY,458731,LF,151,594,96,157,26,...,5,3,254,51,4,165,162,1.02,2890,682
1,2,"Judge, A",NYY,592450,RF,155,542,128,154,24,...,0,4,340,79,15,100,99,1.01,2989,678
2,3,"Gregorius, D",NYY,544369,SS,136,534,73,153,27,...,0,7,255,52,7,135,190,0.71,2069,570
3,4,"Headley, C",NYY,452104,3B,147,512,77,140,30,...,1,7,208,43,10,138,120,1.15,2331,586
4,5,"Sanchez, G",NYY,596142,C,122,471,79,131,20,...,0,4,250,53,9,124,109,1.14,2031,525
5,6,"Castro, S",NYY,516770,2B,112,443,66,133,18,...,0,3,201,35,9,140,89,1.57,1839,473
6,7,"Holliday, M",NYY,407812,DH,105,373,50,86,18,...,0,5,161,37,14,112,80,1.40,1733,427
7,8,"Ellsbury, J",NYY,453056,CF,112,356,65,94,20,...,2,0,143,31,7,113,95,1.19,1563,409
8,9,"Torreyes, R",NYY,591720,2B,108,315,35,92,15,...,5,4,118,19,9,116,82,1.41,1075,336
9,10,"Hicks, A",NYY,543305,CF,88,301,54,80,18,...,1,5,143,33,8,90,78,1.15,1483,361
10,11,"Romine, A",NYY,519222,C,80,229,19,50,9,...,2,3,67,12,7,77,57,1.35,951,252
11,12,"Frazier, T",NYY,453943,3B,66,194,33,43,4,...,0,2,82,16,6,45,62,0.73,995,241
12,13,"Carter, C",NYY,474892,1B,62,184,20,37,5,...,0,2,68,14,5,30,48,0.63,890,208
13,14,"Bird, G",NYY,595885,1B,48,147,20,28,7,...,0,2,62,16,2,31,50,0.62,725,170
14,15,"Frazier, C",NYY,640449,LF,39,134,16,31,9,...,0,1,60,17,2,29,34,0.85,565,142
15,16,"Wade, T",NYY,642180,SS,30,58,7,9,4,...,0,0,13,4,2,19,13,1.46,243,63
16,17,"Cooper, G",NYY,643265,1B,13,43,3,14,5,...,0,1,21,6,0,7,11,0.64,184,45

In [86]:
time.sleep(5)
All_position_element = driver.find_element_by_id('sp_hitting_position')
position_select = Select(All_position_element)

In [87]:
position_select.select_by_visible_text('RF')

In [88]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')
soup = bs4.BeautifulSoup(data_html,"html5lib")
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [89]:
RF=pd.DataFrame(columns = head)

In [90]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)
        
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [91]:
for i in range(2):
    RF.loc[i]= context_b[i]

RF.drop("", axis=1)

,RK,Player,Team,â–²,Pos,G,AB,R,H,2B,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Judge, A",NYY,592450,RF,155,542,128,154,24,...,0,4,340,79,15,100,99,1.01,2989,678
1,2,"Williams, M",NYY,592863,RF,5,16,3,4,0,...,0,0,4,0,0,4,6,0.67,77,17

In [92]:
position_select.select_by_visible_text('CF')

In [93]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')
soup = bs4.BeautifulSoup(data_html,"html5lib")
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [94]:
CF=pd.DataFrame(columns = head)

In [95]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)
        
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [96]:
for i in range(3):
    CF.loc[i]= context_b[i]

CF.drop("", axis=1)

,RK,Player,Team,â–²,Pos,G,AB,R,H,2B,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Ellsbury, J",NYY,453056,CF,112,356,65,94,20,...,2,0,143,31,7,113,95,1.19,1563,409
1,2,"Hicks, A",NYY,543305,CF,88,301,54,80,18,...,1,5,143,33,8,90,78,1.15,1483,361
2,3,"Fowler, D",NYY,641583,CF,1,0,0,0,0,...,0,0,0,0,0,0,0,-.--,0,0

In [97]:
position_select.select_by_visible_text('LF')

In [98]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')
soup = bs4.BeautifulSoup(data_html,"html5lib")
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [99]:
LF=pd.DataFrame(columns = head)

In [100]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)
        
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [101]:
for i in range(2):
    LF.loc[i]= context_b[i]

In [102]:
LF.drop("", axis=1)

,RK,Player,Team,â–²,Pos,G,AB,R,H,2B,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Gardner, B",NYY,458731,LF,151,594,96,157,26,...,5,3,254,51,4,165,162,1.02,2890,682
1,2,"Frazier, C",NYY,640449,LF,39,134,16,31,9,...,0,1,60,17,2,29,34,0.85,565,142

#### Q4 ####

In [103]:
time.sleep(5)
season_select.select_by_index(3)

In [104]:
time.sleep(5)
AL_bar_2017_player = driver.find_element_by_css_selector("#sp_hitting-1 > fieldset:nth-child(1) > label:nth-child(4)")
AL_bar_2017_player.click()

In [105]:
time.sleep(5)
team_element1 = driver.find_element_by_id('sp_hitting_team_id')
team_select1 = Select(team_element1)
team_select1.select_by_visible_text('All Teams')

In [106]:
time.sleep(5)
position_element1 = driver.find_element_by_id('sp_hitting_position')
position_select1 = Select(position_element1)
position_select1.select_by_visible_text('All Positions')

In [107]:
time.sleep(5)
AB_AL_2015_bar = driver.find_element_by_css_selector("th.dg-ab > abbr:nth-child(1)")
AB_AL_2015_bar.click()

In [108]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')
soup = bs4.BeautifulSoup(data_html,"html5lib")
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [109]:
df7=pd.DataFrame(columns = head)

In [110]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)
        
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [112]:
for i in range(50):
    df7.loc[i]= context_b[i]

df7.drop("", axis=1).head()

,RK,Player,Team,â–²,Pos,G,AB,R,H,2B,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Altuve, J",HOU,514888,2B,154,638,86,200,40,...,3,6,293,59,17,198,199,0.99,2227,689
1,2,"Machado, M",BAL,592518,3B,162,633,102,181,30,...,2,4,318,66,17,187,177,1.06,2789,713
2,3,"Calhoun, K",LAA,594777,RF,159,630,78,161,23,...,2,4,266,51,6,165,152,1.09,2557,686
3,4,"Cabrera, M",CWS,466320,LF,158,629,70,172,36,...,2,10,248,50,18,214,185,1.16,2572,683
4,5,"Dozier, B",MIN,572821,2B,157,628,101,148,39,...,0,8,279,71,10,144,206,0.70,2833,704

#### Q5 ####

In [113]:
time.sleep(5)
season_select.select_by_index(4)

In [114]:
time.sleep(5)
MLB_2014_Allstar_bar = driver.find_element_by_css_selector("#sp_hitting-1 > fieldset:nth-child(1) > label:nth-child(2)")
MLB_2014_Allstar_bar.click()

In [115]:
time.sleep(5)
game_element1 = driver.find_element_by_id('sp_hitting_game_type')
game_select1 = Select(game_element1)
game_select1.select_by_visible_text('All-Star Game')

In [116]:
time.sleep(5)
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')
soup = bs4.BeautifulSoup(data_html,"html5lib")
head = [t.text.replace("â–¼","") for t in soup.thead.find_all("th")]

In [117]:
df8=pd.DataFrame(columns = head)

In [118]:
context = []
for t in soup.tbody.find_all("tr"):
    for a in t.find_all("td"):
        context.append(a.text)
        
context_b =[]
for i in range(int(len(context)/len(head))):
    s= context[i*len(head):(i+1)*len(head)]
    context_b.append(s)

In [121]:
for i in range(40):
    df8.loc[i]= context_b[i]

df8.drop("", axis=1)

,RK,Player,Team,â–²,Pos,G,AB,R,H,2B,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Cabrera, M",AL,408234,1B,1,3,1,1,0,...,0,0,4,1,0,0,2,0.00,16,3
1,1,"Goldschmidt, P",NL,502671,1B,1,3,0,0,0,...,0,0,0,0,0,1,1,1.00,7,3
2,1,"McCutchen, A",NL,457705,OF,1,3,0,1,0,...,0,0,1,0,0,1,1,1.00,10,3
3,1,"Puig, Y",NL,624577,OF,1,3,0,0,0,...,0,0,0,0,0,0,0,-,18,3
4,1,"Ramirez, A",NL,133380,3B,1,3,1,2,1,...,0,0,3,1,0,0,1,0.00,9,3
5,1,"Stanton, G",NL,519317,OF,1,3,0,0,0,...,0,0,0,0,0,0,2,0.00,10,3
6,1,"Trout, M",AL,545361,OF,1,3,1,2,1,...,0,0,5,2,0,0,1,0.00,14,3
7,1,"Tulowitzki, T",NL,453064,SS,1,3,0,1,1,...,0,0,2,1,0,0,1,0.00,14,3
8,9,"Bautista, J",AL,430832,OF,1,2,0,0,0,...,0,0,0,0,0,1,0,1.00,9,2
9,9,"Blackmon, C",NL,453568,OF,1,2,0,0,0,...,0,0,0,0,0,1,0,1.00,7,2
10,9,"Cano, R",AL,429664,2B,1,2,0,0,0,...,0,0,0,0,0,0,0,-,8,2
11,9,"Cespedes, Y",AL,493316,OF,1,2,0,0,0,...,0,0,0,0,0,2,0,2.00,5,2
12,9,"Cruz, N",AL,443558,DH,1,2,0,0,0,...,0,0,0,0,0,1,0,1.00,6,2
13,9,"Donaldson, J",AL,518626,3B,1,2,0,0,0,...,0,0,0,0,0,1,0,1.00,10,2
14,9,"Gomez, C",NL,460576,OF,1,2,0,0,0,...,0,0,0,0,0,0,1,0.00,7,2
15,9,"Harrison, J",NL,543281,OF,1,2,0,0,0,...,0,0,0,0,0,0,1,0.00,7,2
16,9,"Jeter, D",AL,116539,SS,1,2,1,2,1,...,0,0,3,1,0,0,0,-,9,2
17,9,"Jones, A",AL,430945,OF,1,2,0,0,0,...,0,0,0,0,0,0,1,0.00,6,2
18,9,"Lucroy, J",NL,518960,C,1,2,0,2,2,...,0,0,4,2,0,0,0,-,9,2
19,9,"Norris, D",AL,519083,C,1,2,1,1,0,...,0,0,1,0,0,0,0,-,7,2
20,9,"Ramirez, A",AL,493351,SS,1,2,1,1,0,...,0,0,1,0,0,1,0,1.00,11,2
21,9,"Seager, K",AL,572122,3B,1,2,0,0,0,...,0,0,0,0,0,2,0,2.00,6,2
22,23,"Abreu, J",AL,547989,1B,1,1,0,0,0,...,0,0,0,0,0,0,1,0.00,1,1
23,23,"Brantley, M",AL,488726,OF,1,1,0,0,0,...,0,0,0,0,0,1,0,1.00,2,1
24,23,"Castro, S",NL,516770,SS,1,1,0,0,0,...,0,0,0,0,0,0,0,-,5,1
25,23,"Freeman, F",NL,518692,1B,1,1,0,1,0,...,0,0,1,0,0,0,0,-,3,1
26,23,"Gordon, D",NL,543829,2B,1,1,1,0,0,...,0,0,0,0,0,1,0,1.00,2,1
27,23,"Kinsler, I",AL,435079,2B,1,1,0,0,0,...,0,0,0,0,0,0,0,-,5,1
28,23,"Mesoraco, D",NL,519023,C,1,1,0,0,0,...,0,0,0,0,0,0,0,-,4,1
29,23,"Montero, M",NL,471083,C,1,1,0,0,0,...,0,0,0,0,0,0,1,0.00,2,1
30,23,"Moss, B",AL,461235,1B,1,1,0,0,0,...,0,0,0,0,0,0,0,-,4,1
31,23,"Murphy, D",NL,502517,2B,1,1,0,0,0,...,0,0,0,0,0,0,0,-,4,1
32,23,"Pence, H",NL,452254,OF,1,1,0,0,0,...,0,0,0,0,0,1,0,1.00,2,1
33,23,"Perez, S",AL,521692,C,1,1,0,0,0,...,0,0,0,0,0,1,0,1.00,3,1
34,23,"Rizzo, A",NL,519203,1B,1,1,0,0,0,...,0,0,0,0,0,0,0,-,5,1
35,23,"Utley, C",NL,400284,2B,1,1,1,1,1,...,0,0,2,1,0,0,0,-,10,2
36,37,"Altuve, J",AL,514888,2B,1,0,0,0,0,...,0,1,0,0,0,0,1,0.00,3,1
37,37,"Aybar, E",AL,430947,SS,1,0,0,0,0,...,0,0,0,0,0,0,0,-,0,0
38,37,"Beltre, A",AL,134181,3B,1,0,0,0,0,...,0,0,0,0,0,0,0,-,4,1
39,37,"Frazier, T",NL,453943,3B,1,0,0,0,0,...,0,0,0,0,0,0,0,-,4,1
40,37,"Suzuki, K",AL,435559,C,1,0,0,0,0,...,0,0,0,0,0,0,0,-,0,0

### Q1 Answer ###

In [124]:
df1.sort_values(by = ['HR'], ascending= False)
max_hr_team_name = df1.iloc[1,1]
max_hr_team_name

'Toronto Blue Jays'

### Q2 Answer ###

#### a) ####

In [134]:
df2.to_csv('/Users/richard/Desktop/660D Web Analytics/2015_AL_data.csv')

In [135]:
df3.to_csv('/Users/richard/Desktop/660D Web Analytics/2015_NL_data.csv')

In [136]:
AL_data_2015 = pd.read_csv('/Users/richard/Desktop/660D Web Analytics/2015_AL_data.csv')
HR_mean_AL= AL_data_2015['HR'].mean()
HR_mean_AL

175.6

In [137]:
NL_data_2015 = pd.read_csv('/Users/richard/Desktop/660D Web Analytics/2015_NL_data.csv')
HR_mean_NL = NL_data_2015['HR'].mean()
HR_mean_NL

151.66666666666666

In [139]:
if HR_mean_AL > HR_mean_NL:
    print('AL')
else:
    print('NL')

AL

#### b) ####

In [140]:
df4.to_csv("/Users/richard/Desktop/660D Web Analytics/2015_AL_data_firstinning.csv")

In [141]:
df5.to_csv('/Users/richard/Desktop/660D Web Analytics/2015_NL_data_firstinning.csv')

In [142]:
AL_data_2015_first_inning=pd.read_csv('/Users/richard/Desktop/660D Web Analytics/2015_AL_data_firstinning.csv')
HR_mean_AL_first_inning= AL_data_2015_first_inning['HR'].mean()
HR_mean_AL_first_inning

23.666666666666668

In [143]:
NL_data_2015_first_inning=pd.read_csv('/Users/richard/Desktop/660D Web Analytics/2015_NL_data_firstinning.csv')
HR_mean_NL_first_inning= NL_data_2015_first_inning['HR'].mean()
HR_mean_NL_first_inning

19.533333333333335

In [144]:
if HR_mean_AL_first_inning > HR_mean_NL_first_inning:
    print('AL')
else:
    print('NL')

AL

### Q3 Answer ###

#### a) ####

In [152]:
new=df6.sort_values(by = ['AVG'], ascending= False)
new

,RK,Player,Team,,â–²,Pos,G,AB,R,H,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
16,17,"Cooper, G",NYY,,643265,1B,13,43,3,14,...,0,1,21,6,0,7,11,0.64,184,45
5,6,"Castro, S",NYY,,516770,2B,112,443,66,133,...,0,3,201,35,9,140,89,1.57,1839,473
8,9,"Torreyes, R",NYY,,591720,2B,108,315,35,92,...,5,4,118,19,9,116,82,1.41,1075,336
2,3,"Gregorius, D",NYY,,544369,SS,136,534,73,153,...,0,7,255,52,7,135,190,0.71,2069,570
1,2,"Judge, A",NYY,,592450,RF,155,542,128,154,...,0,4,340,79,15,100,99,1.01,2989,678
4,5,"Sanchez, G",NYY,,596142,C,122,471,79,131,...,0,4,250,53,9,124,109,1.14,2031,525
3,4,"Headley, C",NYY,,452104,3B,147,512,77,140,...,1,7,208,43,10,138,120,1.15,2331,586
9,10,"Hicks, A",NYY,,543305,CF,88,301,54,80,...,1,5,143,33,8,90,78,1.15,1483,361
7,8,"Ellsbury, J",NYY,,453056,CF,112,356,65,94,...,2,0,143,31,7,113,95,1.19,1563,409
0,1,"Gardner, B",NYY,,458731,LF,151,594,96,157,...,5,3,254,51,4,165,162,1.02,2890,682
6,7,"Holliday, M",NYY,,407812,DH,105,373,50,86,...,0,5,161,37,14,112,80,1.40,1733,427
14,15,"Frazier, C",NYY,,640449,LF,39,134,16,31,...,0,1,60,17,2,29,34,0.85,565,142
11,12,"Frazier, T",NYY,,453943,3B,66,194,33,43,...,0,2,82,16,6,45,62,0.73,995,241
10,11,"Romine, A",NYY,,519222,C,80,229,19,50,...,2,3,67,12,7,77,57,1.35,951,252
12,13,"Carter, C",NYY,,474892,1B,62,184,20,37,...,0,2,68,14,5,30,48,0.63,890,208
13,14,"Bird, G",NYY,,595885,1B,48,147,20,28,...,0,2,62,16,2,31,50,0.62,725,170
15,16,"Wade, T",NYY,,642180,SS,30,58,7,9,...,0,0,13,4,2,19,13,1.46,243,63

In [28]:
new=pd.read_csv('/Users/richard/Desktop/660D Web Analytics/over30_maxavg_player.csv')

In [29]:
max_AVG_Player_name = new.iloc[0,1]
#max_AVG_Player_name
position=new.iloc[0,5]
print('max_AVG_Player_name:','Garrett N. Cooper')
print('position:', position)

max_AVG_Player_name: Garrett N. Cooper
position: 643265

In [154]:
new.to_csv('/Users/richard/Desktop/660D Web Analytics/over30_maxavg_player.csv')

#### b) ####

In [157]:
RFnew=RF.sort_values(by = ['AVG'], ascending= False)
RFnew

,RK,Player,Team,,â–²,Pos,G,AB,R,H,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Judge, A",NYY,,592450,RF,155,542,128,154,...,0,4,340,79,15,100,99,1.01,2989,678
1,2,"Williams, M",NYY,,592863,RF,5,16,3,4,...,0,0,4,0,0,4,6,0.67,77,17

In [161]:
RF_max_AVG_Player_name = RFnew.iloc[0,1]
#max_AVG_Player_name
RF_position=RFnew.iloc[0,5]
print('RF_max_AVG_Player_name:',RF_max_AVG_Player_name)
print('RF_position:', RF_position)

RF_max_AVG_Player_name: Â Judge, A
RF_position: RF

In [162]:
CFnew=CF.sort_values(by = ['AVG'], ascending= False)
CFnew

,RK,Player,Team,,â–²,Pos,G,AB,R,H,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
1,2,"Hicks, A",NYY,,543305,CF,88,301,54,80,...,1,5,143,33,8,90,78,1.15,1483,361
0,1,"Ellsbury, J",NYY,,453056,CF,112,356,65,94,...,2,0,143,31,7,113,95,1.19,1563,409
2,3,"Fowler, D",NYY,,641583,CF,1,0,0,0,...,0,0,0,0,0,0,0,-.--,0,0

In [163]:
CF_max_AVG_Player_name = CFnew.iloc[0,1]
#max_AVG_Player_name
CF_position=CFnew.iloc[0,5]
print('CF_max_AVG_Player_name:',CF_max_AVG_Player_name)
print('CF_position:', CF_position)

CF_max_AVG_Player_name: Â Hicks, A
CF_position: CF

In [166]:
LFnew=LF.sort_values(by = ['AVG'], ascending= False)
LFnew

,RK,Player,Team,,â–²,Pos,G,AB,R,H,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Gardner, B",NYY,,458731,LF,151,594,96,157,...,5,3,254,51,4,165,162,1.02,2890,682
1,2,"Frazier, C",NYY,,640449,LF,39,134,16,31,...,0,1,60,17,2,29,34,0.85,565,142

In [167]:
LF_max_AVG_Player_name = LFnew.iloc[0,1]
#max_AVG_Player_name
LF_position=LFnew.iloc[0,5]
print('LF_max_AVG_Player_name:',LF_max_AVG_Player_name)
print('LF_position:', LF_position)

LF_max_AVG_Player_name: Â Gardner, B
LF_position: LF

In [168]:
RFnew.to_csv('/Users/richard/Desktop/660D Web Analytics/RF.csv')
CFnew.to_csv('/Users/richard/Desktop/660D Web Analytics/CF.csv')
LFnew.to_csv('/Users/richard/Desktop/660D Web Analytics/LF.csv')

### Question 4  Answer ###

In [170]:
AL_regular_2015=df7.sort_values(by = ['AB'], ascending= False)
AL_regular_2015.head()

,RK,Player,Team,,â–²,Pos,G,AB,R,H,...,SAC,SF,TB,XBH,GDP,GO,AO,GO_AO,NP,PA
0,1,"Altuve, J",HOU,,514888,2B,154,638,86,200,...,3,6,293,59,17,198,199,0.99,2227,689
1,2,"Machado, M",BAL,,592518,3B,162,633,102,181,...,2,4,318,66,17,187,177,1.06,2789,713
2,3,"Calhoun, K",LAA,,594777,RF,159,630,78,161,...,2,4,266,51,6,165,152,1.09,2557,686
3,4,"Cabrera, M",CWS,,466320,LF,158,629,70,172,...,2,10,248,50,18,214,185,1.16,2572,683
4,5,"Dozier, B",MIN,,572821,2B,157,628,101,148,...,0,8,279,71,10,144,206,0.70,2833,704

In [173]:
AL_regualr_2015_Player_name = AL_regular_2015.iloc[0,1]
#max_AVG_Player_name
AL_regualr_2015_position=AL_regular_2015.iloc[0,5]
AL_regualr_2015_team=AL_regular_2015.iloc[0,2]
print('AL_regualr_2015_Player_name:',AL_regualr_2015_Player_name)
print('AL_regualr_2015_position:', AL_regualr_2015_position)
print('AL_regualr_2015_team:',AL_regualr_2015_team)

AL_regualr_2015_Player_name: Â Altuve, J
AL_regualr_2015_position: 2B
AL_regualr_2015_team: HOU

In [174]:
AL_regular_2015.to_csv('/Users/richard/Desktop/660D Web Analytics/AL_regular_2015.csv')

### Question 5 Answer ###

In [8]:
latin_coun ='''Argentina;Bolivia;Brazil;Chile;Colombia;Costa Rica;Cuba;Dominican Republic;Ecuador;El Salvador;French Guiana;Guadeloupe;Guatemala;Haiti;Honduras;Martinique;Mexico;Nicaragua;Panama;Paraguay;Peru;Puerto Rico;Saint BarthÃ©lemy;Saint Martin;Uruguay;Venezuela'''

In [9]:
latin_coun_list = latin_coun.split(';')

In [10]:
latin_coun_list

['Argentina',
 'Bolivia',
 'Brazil',
 'Chile',
 'Colombia',
 'Costa Rica',
 'Cuba',
 'Dominican Republic',
 'Ecuador',
 'El Salvador',
 'French Guiana',
 'Guadeloupe',
 'Guatemala',
 'Haiti',
 'Honduras',
 'Martinique',
 'Mexico',
 'Nicaragua',
 'Panama',
 'Paraguay',
 'Peru',
 'Puerto Rico',
 'Saint BarthÃ©lemy',
 'Saint Martin',
 'Uruguay',
 'Venezuela']

In [11]:
player_list=[]
data_div = driver.find_element_by_id('datagrid')
data_html = data_div.get_attribute('innerHTML')
soup = bs4.BeautifulSoup(data_html,"html5lib")
for t in soup.tbody.find_all("tr"):
    player_list.append(t.find_all('td')[1].text.strip())
    #for a in t.find_all("td")[1]:
     #   player_list.append(a.text)

player_list

['Freeman, F',
 'Jeter, D',
 'Lucroy, J',
 'Utley, C',
 'Ramirez, A',
 'Trout, M',
 'Norris, D',
 'Ramirez, A',
 'Cabrera, M',
 'McCutchen, A',
 'Tulowitzki, T',
 'Abreu, J',
 'Bautista, J',
 'Blackmon, C',
 'Brantley, M',
 'Cano, R',
 'Castro, S',
 'Cespedes, Y',
 'Cruz, N',
 'Donaldson, J',
 'Goldschmidt, P',
 'Gomez, C',
 'Gordon, D',
 'Harrison, J',
 'Jones, A',
 'Kinsler, I',
 'Mesoraco, D',
 'Montero, M',
 'Moss, B',
 'Murphy, D',
 'Pence, H',
 'Perez, S',
 'Puig, Y',
 'Rizzo, A',
 'Seager, K',
 'Stanton, G',
 'Altuve, J',
 'Aybar, E',
 'Beltre, A',
 'Frazier, T',
 'Suzuki, K']

In [23]:
data=[]
for a in player_list:
    player_name_bar = driver.find_element_by_link_text(a)
    #player_name = driver.find_element_by_css_selector('#_715571520275262687 > tbody:nth-child(36) > tr:nth-child(1) > td:nth-child(2) > a:nth-child(1)')
    player_name_bar.click()
    wait = WebDriverWait(driver, 10)
    player_bio= wait.until(EC.visibility_of_element_located((By.CLASS_NAME, 'player-bio')))
    #p_born = driver.find_element_by_css_selector('div.player-bio:nth-child(2) > ul:nth-child(2) > li:nth-child(4) > span:nth-child(1)').text
    for a in latin_coun_list:
        if a in player_bio.text:
            
        #born = a.find_element_by_class_name('player-bio').text
            #if country in born:
            player_name=driver.find_element_by_class_name('full-name').text
            normal_delay = random.normalvariate(3, 0.5)
            time.sleep(normal_delay)
            #player_team=driver.find_element_by_class_name('dropdown.team')
            datahtml= wait.until(EC.visibility_of_element_located((By.CLASS_NAME, 'dropdown.team'))).text
            #datahtml=driver.find_element_by_class_name('dropdown.team').text
            team_name = datahtml.split('\n')[0].strip()
            #soup = bs4.BeautifulSoup(datahtml,"html5lib")
            #player_team_update=soup.find('span', attrs={'data-bind': 'text: selectedTeamLabel'}).text
            print('player_name:',player_name)
            data.append(player_name)
            print('team_name:', team_name)
            data.append(team_name)
    
    driver.back()
    normal_delay = random.normalvariate(3, 0.5)
    time.sleep(normal_delay)

player_name: Aramis Nin Ramirez
team_name: Pittsburgh Pirates
player_name: Aramis Nin Ramirez
team_name: Pittsburgh Pirates
player_name: Jose Miguel Cabrera
team_name: Detroit Tigers
player_name: JosÃ© Dariel Abreu
team_name: Chicago White Sox
player_name: JosÃ© Antonio Bautista
team_name: Toronto Blue Jays
player_name: Robinson Jose CanÃ³
team_name: Seattle Mariners
player_name: Starlin DeJesus Castro
team_name: Miami Marlins
player_name: Yoenis CÃ©spedes
team_name: New York Mets
player_name: Nelson Ramon Cruz
team_name: Seattle Mariners
player_name: Carlos Argelis GÃ³mez
team_name: Tampa Bay Rays
player_name: Miguel Angel Montero
team_name: Washington Nationals
player_name: Salvador Johan Perez
team_name: Kansas City Royals
player_name: Yasiel Puig
team_name: Los Angeles Dodgers
player_name: JosÃ© Carlos Altuve
team_name: Houston Astros
player_name: Erick Johan Aybar
team_name: Minnesota Twins
player_name: Adrian Beltre
team_name: Texas Rangers

In [27]:
head = ['Players','Team']
context_5 =[]
for i in range(int(len(data)/len(head))):
    s= data[i*len(head):(i+1)*len(head)]
    context_5.append(s) 
context_5

[['Aramis Nin Ramirez', 'Pittsburgh Pirates'],
 ['Aramis Nin Ramirez', 'Pittsburgh Pirates'],
 ['Jose Miguel Cabrera', 'Detroit Tigers'],
 ['JosÃ© Dariel Abreu', 'Chicago White Sox'],
 ['JosÃ© Antonio Bautista', 'Toronto Blue Jays'],
 ['Robinson Jose CanÃ³', 'Seattle Mariners'],
 ['Starlin DeJesus Castro', 'Miami Marlins'],
 ['Yoenis CÃ©spedes', 'New York Mets'],
 ['Nelson Ramon Cruz', 'Seattle Mariners'],
 ['Carlos Argelis GÃ³mez', 'Tampa Bay Rays'],
 ['Miguel Angel Montero', 'Washington Nationals'],
 ['Salvador Johan Perez', 'Kansas City Royals'],
 ['Yasiel Puig', 'Los Angeles Dodgers'],
 ['JosÃ© Carlos Altuve', 'Houston Astros'],
 ['Erick Johan Aybar', 'Minnesota Twins'],
 ['Adrian Beltre', 'Texas Rangers']]

In [31]:
head = ['Players','Team']
df_q5=pd.DataFrame(columns= head)
for i in range(16):
    df_q5.loc[i]= context_5[i]
df_q5.to_csv('/Users/richard/Desktop/660D Web Analytics/q5.csv')

### Question 6 ###

In [32]:
import http.client, urllib.request, urllib.parse, urllib.error, base64
import json

In [33]:
def api(html):
    headers = {
    # Request headers
    'Ocp-Apim-Subscription-Key': 'eb565a0b452d454fb465d9f11e50ac0a',
}
    
    conn = http.client.HTTPSConnection('api.fantasydata.net')
    conn.request("GET", html, "{body}", headers)
    response = conn.getresponse()
    data = response.read()
    return data

In [34]:
data2=api("/v3/mlb/stats/json/Stadiums")

In [35]:
data2= json.loads(data2)
data2

[{'Active': True,
  'Altitude': 14,
  'Capacity': 41164,
  'CenterField': 396,
  'City': 'San Diego',
  'Country': 'USA',
  'GeoLat': 32.70771,
  'GeoLong': -117.157097,
  'HomePlateDirection': 180,
  'LeftCenterField': 367,
  'LeftField': 334,
  'MidLeftCenterField': 402,
  'MidLeftField': 351,
  'MidRightCenterField': 403,
  'MidRightField': 351,
  'Name': 'PETCO Park',
  'RightCenterField': 378,
  'RightField': 322,
  'StadiumID': 1,
  'State': 'CA',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': 939,
  'Capacity': 49586,
  'CenterField': 401,
  'City': 'Atlanta',
  'Country': 'USA',
  'GeoLat': 33.734805,
  'GeoLong': -84.389996,
  'HomePlateDirection': 150,
  'LeftCenterField': 380,
  'LeftField': 335,
  'MidLeftCenterField': 394,
  'MidLeftField': 360,
  'MidRightCenterField': 394,
  'MidRightField': 358,
  'Name': 'Turner Field',
  'RightCenterField': 390,
  'RightField': 330,
  'StadiumID': 2,
  'State': 'GA',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Salt River Fields at Talking Stick',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 3,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Cubs Park',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 4,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'JetBlue Park',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 5,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Hammond Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 6,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Peoria Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 7,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 13,
  'Capacity': 41922,
  'CenterField': 408,
  'City': 'New York',
  'Country': 'USA',
  'GeoLat': 40.756337,
  'GeoLong': -73.846043,
  'HomePlateDirection': 165,
  'LeftCenterField': 384,
  'LeftField': 335,
  'MidLeftCenterField': 394,
  'MidLeftField': 371,
  'MidRightCenterField': 415,
  'MidRightField': 372,
  'Name': 'Citi Field',
  'RightCenterField': 378,
  'RightField': 330,
  'StadiumID': 8,
  'State': 'NY',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'State Mutual Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 9,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 673,
  'Capacity': 37675,
  'CenterField': 405,
  'City': 'Cleveland',
  'Country': 'USA',
  'GeoLat': 41.496192,
  'GeoLong': -81.685238,
  'HomePlateDirection': 180,
  'LeftCenterField': 368,
  'LeftField': 325,
  'MidLeftCenterField': 385,
  'MidLeftField': 369,
  'MidRightCenterField': 388,
  'MidRightField': 364,
  'Name': 'Progressive Field',
  'RightCenterField': 375,
  'RightField': 325,
  'StadiumID': 10,
  'State': 'OH',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'NL City',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 11,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'TBD',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 12,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 8,
  'Capacity': 41915,
  'CenterField': 399,
  'City': 'San Francisco',
  'Country': 'USA',
  'GeoLat': 37.778473,
  'GeoLong': -122.389595,
  'HomePlateDirection': 90,
  'LeftCenterField': 382,
  'LeftField': 339,
  'MidLeftCenterField': 389,
  'MidLeftField': 346,
  'MidRightCenterField': 399,
  'MidRightField': 368,
  'Name': 'AT&amp;T Park',
  'RightCenterField': 421,
  'RightField': 309,
  'StadiumID': 13,
  'State': 'CA',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': 840,
  'Capacity': 39021,
  'CenterField': 404,
  'City': 'Minneapolis',
  'Country': 'USA',
  'GeoLat': 44.981713,
  'GeoLong': -93.277347,
  'HomePlateDirection': 105,
  'LeftCenterField': 377,
  'LeftField': 339,
  'MidLeftCenterField': 390,
  'MidLeftField': 355,
  'MidRightCenterField': 392,
  'MidRightField': 344,
  'Name': 'Target Field',
  'RightCenterField': 367,
  'RightField': 328,
  'StadiumID': 14,
  'State': 'MN',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'McKechnie Field',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 15,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Louisville Slugger Field',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 16,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Champion Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 17,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 41,
  'Capacity': 31042,
  'CenterField': 404,
  'City': 'St. Petersburg',
  'Country': 'USA',
  'GeoLat': 27.76816,
  'GeoLong': -82.653465,
  'HomePlateDirection': 135,
  'LeftCenterField': 370,
  'LeftField': 315,
  'MidLeftCenterField': 410,
  'MidLeftField': 354,
  'MidRightCenterField': 404,
  'MidRightField': 342,
  'Name': 'Tropicana Field',
  'RightCenterField': 370,
  'RightField': 322,
  'StadiumID': 18,
  'State': 'FL',
  'Surface': 'AstroTurf',
  'Type': 'Dome'},
 {'Active': True,
  'Altitude': 602,
  'Capacity': 41900,
  'CenterField': 400,
  'City': 'Milwaukee',
  'Country': 'USA',
  'GeoLat': 43.027982,
  'GeoLong': -87.971165,
  'HomePlateDirection': 45,
  'LeftCenterField': 370,
  'LeftField': 344,
  'MidLeftCenterField': 379,
  'MidLeftField': 359,
  'MidRightCenterField': 386,
  'MidRightField': 354,
  'Name': 'Miller Park',
  'RightCenterField': 374,
  'RightField': 345,
  'StadiumID': 19,
  'State': 'WI',
  'Surface': 'Grass',
  'Type': 'RetractableDome'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'AutoZone Park',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 20,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 549,
  'Capacity': 48114,
  'CenterField': 400,
  'City': 'Arlington',
  'Country': 'USA',
  'GeoLat': 32.751147,
  'GeoLong': -97.082454,
  'HomePlateDirection': 45,
  'LeftCenterField': 390,
  'LeftField': 354,
  'MidLeftCenterField': 406,
  'MidLeftField': 357,
  'MidRightCenterField': 407,
  'MidRightField': 356,
  'Name': 'Globe Life Park in Arlington',
  'RightCenterField': 379,
  'RightField': 349,
  'StadiumID': 21,
  'State': 'TX',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': 35,
  'Capacity': 45971,
  'CenterField': 410,
  'City': 'Baltimore',
  'Country': 'USA',
  'GeoLat': 39.283964,
  'GeoLong': -76.621618,
  'HomePlateDirection': 150,
  'LeftCenterField': 364,
  'LeftField': 333,
  'MidLeftCenterField': 378,
  'MidLeftField': 368,
  'MidRightCenterField': 400,
  'MidRightField': 341,
  'Name': 'Oriole Park at Camden Yards',
  'RightCenterField': 373,
  'RightField': 318,
  'StadiumID': 22,
  'State': 'MD',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': 0,
  'Capacity': 35067,
  'CenterField': 400,
  'City': 'Oakland',
  'Country': 'USA',
  'GeoLat': 37.751605,
  'GeoLong': -122.200523,
  'HomePlateDirection': 135,
  'LeftCenterField': 362,
  'LeftField': 330,
  'MidLeftCenterField': 388,
  'MidLeftField': 367,
  'MidRightCenterField': 388,
  'MidRightField': 367,
  'Name': 'O.co Coliseum',
  'RightCenterField': 362,
  'RightField': 330,
  'StadiumID': 23,
  'State': 'CA',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Florida Auto Exchange Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 24,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 594,
  'Capacity': 40615,
  'CenterField': 400,
  'City': 'Chicago',
  'Country': 'USA',
  'GeoLat': 41.829908,
  'GeoLong': -87.63354,
  'HomePlateDirection': 45,
  'LeftCenterField': 377,
  'LeftField': 330,
  'MidLeftCenterField': 385,
  'MidLeftField': 365,
  'MidRightCenterField': 385,
  'MidRightField': 365,
  'Name': 'U.S. Cellular Field',
  'RightCenterField': 372,
  'RightField': 335,
  'StadiumID': 25,
  'State': 'IL',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Olympic Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 26,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 599,
  'Capacity': 40929,
  'CenterField': 400,
  'City': 'Chicago',
  'Country': 'USA',
  'GeoLat': 41.947856,
  'GeoLong': -87.655887,
  'HomePlateDirection': 150,
  'LeftCenterField': 368,
  'LeftField': 355,
  'MidLeftCenterField': 391,
  'MidLeftField': 356,
  'MidRightCenterField': 397,
  'MidRightField': 356,
  'Name': 'Wrigley Field',
  'RightCenterField': 368,
  'RightField': 353,
  'StadiumID': 27,
  'State': 'IL',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': 154,
  'Capacity': 43250,
  'CenterField': 408,
  'City': 'Anaheim',
  'Country': 'USA',
  'GeoLat': 33.799925,
  'GeoLong': -117.883194,
  'HomePlateDirection': 135,
  'LeftCenterField': 376,
  'LeftField': 330,
  'MidLeftCenterField': 387,
  'MidLeftField': 348,
  'MidRightCenterField': 383,
  'MidRightField': 359,
  'Name': 'Angel Stadium of Anaheim',
  'RightCenterField': 362,
  'RightField': 330,
  'StadiumID': 28,
  'State': 'CA',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': 724,
  'Capacity': 38362,
  'CenterField': 399,
  'City': 'Pittsburgh',
  'Country': 'USA',
  'GeoLat': 40.447307,
  'GeoLong': -80.006841,
  'HomePlateDirection': 60,
  'LeftCenterField': 389,
  'LeftField': 325,
  'MidLeftCenterField': 410,
  'MidLeftField': 370,
  'MidRightCenterField': 393,
  'MidRightField': 353,
  'Name': 'PNC Park',
  'RightCenterField': 375,
  'RightField': 320,
  'StadiumID': 29,
  'State': 'PA',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Tradition Field',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 30,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 501,
  'Capacity': 56000,
  'CenterField': 395,
  'City': 'Los Angeles',
  'Country': 'USA',
  'GeoLat': 34.072724,
  'GeoLong': -118.240646,
  'HomePlateDirection': 150,
  'LeftCenterField': 385,
  'LeftField': 330,
  'MidLeftCenterField': 390,
  'MidLeftField': 380,
  'MidRightCenterField': 390,
  'MidRightField': 380,
  'Name': 'Dodger Stadium',
  'RightCenterField': 385,
  'RightField': 330,
  'StadiumID': 31,
  'State': 'CA',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Tempe Diablo Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 32,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 886,
  'Capacity': 37903,
  'CenterField': 410,
  'City': 'Kansas City',
  'Country': 'USA',
  'GeoLat': 39.051098,
  'GeoLong': -94.481115,
  'HomePlateDirection': 135,
  'LeftCenterField': 387,
  'LeftField': 330,
  'MidLeftCenterField': 390,
  'MidLeftField': 351,
  'MidRightCenterField': 390,
  'MidRightField': 351,
  'Name': 'Kauffman Stadium',
  'RightCenterField': 387,
  'RightField': 330,
  'StadiumID': 33,
  'State': 'MO',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Roger Dean Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 34,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': 11,
  'Capacity': 49642,
  'CenterField': 408,
  'City': 'New York',
  'Country': 'USA',
  'GeoLat': 40.829327,
  'GeoLong': -73.927735,
  'HomePlateDirection': 105,
  'LeftCenterField': 399,
  'LeftField': 318,
  'MidLeftCenterField': 400,
  'MidLeftField': 357,
  'MidRightCenterField': 396,
  'MidRightField': 346,
  'Name': 'Yankee Stadium',
  'RightCenterField': 385,
  'RightField': 314,
  'StadiumID': 35,
  'State': 'NY',
  'Surface': 'Grass',
  'Type': 'Outdoor'},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Montgomery Riverwalk Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 36,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Harbor Park',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 37,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Osceola County Stadium',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 38,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Bright House Field',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 39,
  'State': None,
  'Surface': None,
  'Type': None},
 {'Active': True,
  'Altitude': None,
  'Capacity': None,
  'CenterField': None,
  'City': None,
  'Country': None,
  'GeoLat': None,
  'GeoLong': None,
  'HomePlateDirection': None,
  'LeftCenterField': None,
  'LeftField': None,
  'MidLeftCenterField': None,
  'MidLeftField': None,
  'MidRightCenterField': None,
  'MidRightField': None,
  'Name': 'Sydney Cricket Ground',
  'RightCenterField': None,
  'RightField': None,
  'StadiumID': 40,
  'State': None,

In [36]:
context_2 =[]
for i in data2:
    context_2.append([i["StadiumID"],i["Name"],i["City"],i["State"]])
context_2

[[1, 'PETCO Park', 'San Diego', 'CA'],
 [2, 'Turner Field', 'Atlanta', 'GA'],
 [3, 'Salt River Fields at Talking Stick', None, None],
 [4, 'Cubs Park', None, None],
 [5, 'JetBlue Park', None, None],
 [6, 'Hammond Stadium', None, None],
 [7, 'Peoria Stadium', None, None],
 [8, 'Citi Field', 'New York', 'NY'],
 [9, 'State Mutual Stadium', None, None],
 [10, 'Progressive Field', 'Cleveland', 'OH'],
 [11, 'NL City', None, None],
 [12, 'TBD', None, None],
 [13, 'AT&amp;T Park', 'San Francisco', 'CA'],
 [14, 'Target Field', 'Minneapolis', 'MN'],
 [15, 'McKechnie Field', None, None],
 [16, 'Louisville Slugger Field', None, None],
 [17, 'Champion Stadium', None, None],
 [18, 'Tropicana Field', 'St. Petersburg', 'FL'],
 [19, 'Miller Park', 'Milwaukee', 'WI'],
 [20, 'AutoZone Park', None, None],
 [21, 'Globe Life Park in Arlington', 'Arlington', 'TX'],
 [22, 'Oriole Park at Camden Yards', 'Baltimore', 'MD'],
 [23, 'O.co Coliseum', 'Oakland', 'CA'],
 [24, 'Florida Auto Exchange Stadium', None, None],
 [25, 'U.S. Cellular Field', 'Chicago', 'IL'],
 [26, 'Olympic Stadium', None, None],
 [27, 'Wrigley Field', 'Chicago', 'IL'],
 [28, 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 [29, 'PNC Park', 'Pittsburgh', 'PA'],
 [30, 'Tradition Field', None, None],
 [31, 'Dodger Stadium', 'Los Angeles', 'CA'],
 [32, 'Tempe Diablo Stadium', None, None],
 [33, 'Kauffman Stadium', 'Kansas City', 'MO'],
 [34, 'Roger Dean Stadium', None, None],
 [35, 'Yankee Stadium', 'New York', 'NY'],
 [36, 'Montgomery Riverwalk Stadium', None, None],
 [37, 'Harbor Park', None, None],
 [38, 'Osceola County Stadium', None, None],
 [39, 'Bright House Field', None, None],
 [40, 'Sydney Cricket Ground', None, None],
 [41, 'Busch Stadium', 'St. Louis', 'MO'],
 [42, 'Rogers Centre', 'Toronto', 'ON'],
 [43, 'Phoenix Municipal Stadium', None, None],
 [44, 'Coors Field', 'Denver', 'CO'],
 [45, 'Goodyear Ballpark', None, None],
 [46, 'AL City', None, None],
 [47, 'Pensacola Bayfront Stadium', None, None],
 [48, 'Alamodome', None, None],
 [49, 'Ed Smith Stadium', None, None],
 [50, 'Fenway Park', 'Boston', 'MA'],
 [51, 'Citizens Bank Park', 'Philadelphia', 'PA'],
 [52, 'Regions Field', None, None],
 [53, 'Nationals Park', 'Washington', 'DC'],
 [54, 'Chase Field', 'Phoenix', 'AZ'],
 [55, 'Scottsdale Stadium', None, None],
 [56, 'Surprise Stadium', None, None],
 [57, 'Marlins Park', 'Miami', 'FL'],
 [58, 'Charlotte Sports Park', None, None],
 [59, 'Maryvale Baseball Park', None, None],
 [60, 'Space Coast Stadium', None, None],
 [61, 'Camelback Ranch', None, None],
 [62, 'Comerica Park', 'Detroit', 'MI'],
 [63, 'Minute Maid Park', 'Houston', 'TX'],
 [64, 'Great American Ball Park', 'Cincinnati', 'OH'],
 [65, 'Safeco Field', 'Seattle', 'WA'],
 [66, 'George M. Steinbrenner Field', None, None],
 [67, 'Joker Marchant Stadium', None, None],
 [68, 'SunTrust Park', 'Atlanta', 'GA']]

In [37]:
data3=api("/v3/mlb/stats/json/Games/2016")

In [38]:
data4= json.loads(data3)

In [39]:
context=[]
for i in data4:
    context.append([i["HomeTeam"],i["AwayTeam"],i["DateTime"][0:10],i["StadiumID"]])
context

[['KC', 'NYM', '2016-04-03', 33],
 ['PIT', 'STL', '2016-04-03', 29],
 ['TB', 'TOR', '2016-04-03', 18],
 ['MIL', 'SF', '2016-04-04', 19],
 ['LAA', 'CHC', '2016-04-04', 28],
 ['ARI', 'COL', '2016-04-04', 54],
 ['NYY', 'HOU', '2016-04-04', 35],
 ['CLE', 'BOS', '2016-04-04', 10],
 ['CIN', 'PHI', '2016-04-04', 64],
 ['BAL', 'MIN', '2016-04-04', 22],
 ['TB', 'TOR', '2016-04-04', 18],
 ['SD', 'LAD', '2016-04-04', 1],
 ['TEX', 'SEA', '2016-04-04', 21],
 ['OAK', 'CHW', '2016-04-04', 23],
 ['ATL', 'WSH', '2016-04-04', 2],
 ['MIA', 'DET', '2016-04-05', 57],
 ['CLE', 'BOS', '2016-04-05', 10],
 ['ARI', 'COL', '2016-04-05', 54],
 ['LAA', 'CHC', '2016-04-05', 28],
 ['SD', 'LAD', '2016-04-05', 1],
 ['MIL', 'SF', '2016-04-05', 19],
 ['NYY', 'HOU', '2016-04-05', 35],
 ['OAK', 'CHW', '2016-04-05', 23],
 ['KC', 'NYM', '2016-04-05', 33],
 ['PIT', 'STL', '2016-04-05', 29],
 ['TB', 'TOR', '2016-04-05', 18],
 ['TEX', 'SEA', '2016-04-05', 21],
 ['BAL', 'MIN', '2016-04-06', 22],
 ['MIA', 'DET', '2016-04-06', 57],
 ['NYY', 'HOU', '2016-04-06', 35],
 ['TB', 'TOR', '2016-04-06', 18],
 ['PIT', 'STL', '2016-04-06', 29],
 ['CLE', 'BOS', '2016-04-06', 10],
 ['ATL', 'WSH', '2016-04-06', 2],
 ['ARI', 'COL', '2016-04-06', 54],
 ['TEX', 'SEA', '2016-04-06', 21],
 ['CIN', 'PHI', '2016-04-06', 64],
 ['OAK', 'CHW', '2016-04-06', 23],
 ['MIL', 'SF', '2016-04-06', 19],
 ['SD', 'LAD', '2016-04-06', 1],
 ['ARI', 'CHC', '2016-04-07', 54],
 ['CLE', 'BOS', '2016-04-07', 10],
 ['SF', 'LAD', '2016-04-07', 13],
 ['NYY', 'HOU', '2016-04-07', 35],
 ['LAA', 'TEX', '2016-04-07', 28],
 ['BAL', 'MIN', '2016-04-07', 22],
 ['CIN', 'PHI', '2016-04-07', 64],
 ['OAK', 'CHW', '2016-04-07', 23],
 ['WSH', 'MIA', '2016-04-07', 53],
 ['SEA', 'OAK', '2016-04-08', 65],
 ['MIL', 'HOU', '2016-04-08', 19],
 ['LAA', 'TEX', '2016-04-08', 28],
 ['ARI', 'CHC', '2016-04-08', 54],
 ['CHW', 'CLE', '2016-04-08', 25],
 ['CIN', 'PIT', '2016-04-08', 64],
 ['COL', 'SD', '2016-04-08', 44],
 ['TOR', 'BOS', '2016-04-08', 42],
 ['SF', 'LAD', '2016-04-08', 13],
 ['DET', 'NYY', '2016-04-08', 62],
 ['NYM', 'PHI', '2016-04-08', 8],
 ['ATL', 'STL', '2016-04-08', 2],
 ['BAL', 'TB', '2016-04-08', 22],
 ['KC', 'MIN', '2016-04-08', 33],
 ['COL', 'SD', '2016-04-09', 44],
 ['CHW', 'CLE', '2016-04-09', 25],
 ['WSH', 'MIA', '2016-04-09', 53],
 ['BAL', 'TB', '2016-04-09', 22],
 ['ATL', 'STL', '2016-04-09', 2],
 ['LAA', 'TEX', '2016-04-09', 28],
 ['ARI', 'CHC', '2016-04-09', 54],
 ['MIL', 'HOU', '2016-04-09', 19],
 ['KC', 'MIN', '2016-04-09', 33],
 ['DET', 'NYY', '2016-04-09', 62],
 ['NYM', 'PHI', '2016-04-09', 8],
 ['SEA', 'OAK', '2016-04-09', 65],
 ['SF', 'LAD', '2016-04-09', 13],
 ['CIN', 'PIT', '2016-04-09', 64],
 ['TOR', 'BOS', '2016-04-09', 42],
 ['NYM', 'PHI', '2016-04-10', 8],
 ['KC', 'MIN', '2016-04-10', 33],
 ['CIN', 'PIT', '2016-04-10', 64],
 ['WSH', 'MIA', '2016-04-10', 53],
 ['MIL', 'HOU', '2016-04-10', 19],
 ['SF', 'LAD', '2016-04-10', 13],
 ['COL', 'SD', '2016-04-10', 44],
 ['TOR', 'BOS', '2016-04-10', 42],
 ['CHW', 'CLE', '2016-04-10', 25],
 ['DET', 'NYY', '2016-04-10', 62],
 ['ATL', 'STL', '2016-04-10', 2],
 ['ARI', 'CHC', '2016-04-10', 54],
 ['LAA', 'TEX', '2016-04-10', 28],
 ['SEA', 'OAK', '2016-04-10', 65],
 ['BAL', 'TB', '2016-04-10', 22],
 ['BOS', 'BAL', '2016-04-11', 50],
 ['WSH', 'ATL', '2016-04-11', 53],
 ['CHC', 'CIN', '2016-04-11', 27],
 ['DET', 'PIT', '2016-04-11', 62],
 ['MIN', 'CHW', '2016-04-11', 14],
 ['STL', 'MIL', '2016-04-11', 41],
 ['SEA', 'TEX', '2016-04-11', 65],
 ['HOU', 'KC', '2016-04-11', 63],
 ['OAK', 'LAA', '2016-04-11', 23],
 ['PHI', 'SD', '2016-04-11', 51],
 ['NYM', 'MIA', '2016-04-11', 8],
 ['NYM', 'MIA', '2016-04-12', 8],
 ['HOU', 'KC', '2016-04-12', 63],
 ['LAD', 'ARI', '2016-04-12', 31],
 ['DET', 'PIT', '2016-04-12', 62],
 ['TB', 'CLE', '2016-04-12', 18],
 ['COL', 'SF', '2016-04-12', 44],
 ['SEA', 'TEX', '2016-04-12', 65],
 ['BOS', 'BAL', '2016-04-12', 50],
 ['WSH', 'ATL', '2016-04-12', 53],
 ['TOR', 'NYY', '2016-04-12', 42],
 ['OAK', 'LAA', '2016-04-12', 23],
 ['PHI', 'SD', '2016-04-12', 51],
 ['LAD', 'ARI', '2016-04-13', 31],
 ['BOS', 'BAL', '2016-04-13', 50],
 ['OAK', 'LAA', '2016-04-13', 23],
 ['CHC', 'CIN', '2016-04-13', 27],
 ['PIT', 'DET', '2016-04-13', 29],
 ['MIN', 'CHW', '2016-04-13', 14],
 ['SEA', 'TEX', '2016-04-13', 65],
 ['HOU', 'KC', '2016-04-13', 63],
 ['TOR', 'NYY', '2016-04-13', 42],
 ['COL', 'SF', '2016-04-13', 44],
 ['TB', 'CLE', '2016-04-13', 18],
 ['STL', 'MIL', '2016-04-13', 41],
 ['NYM', 'MIA', '2016-04-13', 8],
 ['WSH', 'ATL', '2016-04-13', 53],
 ['PHI', 'SD', '2016-04-13', 51],
 ['MIN', 'CHW', '2016-04-14', 14],
 ['STL', 'MIL', '2016-04-14', 41],
 ['WSH', 'ATL', '2016-04-14', 53],
 ['TEX', 'BAL', '2016-04-14', 21],
 ['LAD', 'ARI', '2016-04-14', 31],
 ['CHC', 'CIN', '2016-04-14', 27],
 ['HOU', 'KC', '2016-04-14', 63],
 ['TB', 'CLE', '2016-04-14', 18],
 ['COL', 'SF', '2016-04-14', 44],
 ['TOR', 'NYY', '2016-04-14', 42],
 ['PHI', 'SD', '2016-04-14', 51],
 ['PIT', 'DET', '2016-04-14', 29],
 ['PHI', 'WSH', '2016-04-15', 51],
 ['MIA', 'ATL', '2016-04-15', 57],
 ['HOU', 'DET', '2016-04-15', 63],
 ['MIN', 'LAA', '2016-04-15', 14],
 ['PIT', 'MIL', '2016-04-15', 29],
 ['OAK', 'KC', '2016-04-15', 23],
 ['LAD', 'SF', '2016-04-15', 31],
 ['SD', 'ARI', '2016-04-15', 1],
 ['TEX', 'BAL', '2016-04-15', 21],
 ['TB', 'CHW', '2016-04-15', 18],
 ['BOS', 'TOR', '2016-04-15', 50],
 ['CHC', 'COL', '2016-04-15', 27],
 ['CLE', 'NYM', '2016-04-15', 10],
 ['NYY', 'SEA', '2016-04-15', 35],
 ['STL', 'CIN', '2016-04-15', 41],
 ['MIN', 'LAA', '2016-04-16', 14],
 ['HOU', 'DET', '2016-04-16', 63],
 ['CLE', 'NYM', '2016-04-16', 10],
 ['MIA', 'ATL', '2016-04-16', 57],
 ['PIT', 'MIL', '2016-04-16', 29],
 ['SD', 'ARI', '2016-04-16', 1],
 ['TEX', 'BAL', '2016-04-16', 21],
 ['TB', 'CHW', '2016-04-16', 18],
 ['CHC', 'COL', '2016-04-16', 27],
 ['PHI', 'WSH', '2016-04-16', 51],
 ['BOS', 'TOR', '2016-04-16', 50],
 ['STL', 'CIN', '2016-04-16', 41],
 ['OAK', 'KC', '2016-04-16', 23],
 ['NYY', 'SEA', '2016-04-16', 35],
 ['LAD', 'SF', '2016-04-16', 31],
 ['CLE', 'NYM', '2016-04-17', 10],
 ['MIA', 'ATL', '2016-04-17', 57],
 ['CHC', 'COL', '2016-04-17', 27],
 ['TB', 'CHW', '2016-04-17', 18],
 ['LAD', 'SF', '2016-04-17', 31],
 ['BOS', 'TOR', '2016-04-17', 50],
 ['TEX', 'BAL', '2016-04-17', 21],
 ['OAK', 'KC', '2016-04-17', 23],
 ['HOU', 'DET', '2016-04-17', 63],
 ['MIN', 'LAA', '2016-04-17', 14],
 ['SD', 'ARI', '2016-04-17', 1],
 ['PHI', 'WSH', '2016-04-17', 51],
 ['NYY', 'SEA', '2016-04-17', 35],
 ['STL', 'CIN', '2016-04-17', 41],
 ['PIT', 'MIL', '2016-04-17', 29],
 ['MIN', 'MIL', '2016-04-18', 14],
 ['BOS', 'TOR', '2016-04-18', 50],
 ['STL', 'CHC', '2016-04-18', 41],
 ['PHI', 'NYM', '2016-04-18', 51],
 ['CHW', 'LAA', '2016-04-18', 25],
 ['CIN', 'COL', '2016-04-18', 64],
 ['MIA', 'WSH', '2016-04-18', 57],
 ['SF', 'ARI', '2016-04-18', 13],
 ['CIN', 'COL', '2016-04-19', 64],
 ['CLE', 'SEA', '2016-04-19', 10],
 ['BAL', 'TOR', '2016-04-19', 22],
 ['BOS', 'TB', '2016-04-19', 50],
 ['ATL', 'LAD', '2016-04-19', 2],
 ['CHW', 'LAA', '2016-04-19', 25],
 ['KC', 'DET', '2016-04-19', 33],
 ['TEX', 'HOU', '2016-04-19', 21],
 ['SF', 'ARI', '2016-04-19', 13],
 ['STL', 'CHC', '2016-04-19', 41],
 ['MIN', 'MIL', '2016-04-19', 14],
 ['SD', 'PIT', '2016-04-19', 1],
 ['MIA', 'WSH', '2016-04-19', 57],
 ['PHI', 'NYM', '2016-04-19', 51],
 ['NYY', 'OAK', '2016-04-19', 35],
 ['CHW', 'LAA', '2016-04-20', 25],
 ['MIL', 'MIN', '2016-04-20', 19],
 ['MIA', 'WSH', '2016-04-20', 57],
 ['ATL', 'LAD', '2016-04-20', 2],
 ['CLE', 'SEA', '2016-04-20', 10],
 ['CIN', 'COL', '2016-04-20', 64],
 ['STL', 'CHC', '2016-04-20', 41],
 ['TEX', 'HOU', '2016-04-20', 21],
 ['SD', 'PIT', '2016-04-20', 1],
 ['KC', 'DET', '2016-04-20', 33],
 ['NYY', 'OAK', '2016-04-20', 35],
 ['PHI', 'NYM', '2016-04-20', 51],
 ['BOS', 'TB', '2016-04-20', 50],
 ['SF', 'ARI', '2016-04-20', 13],
 ['BAL', 'TOR', '2016-04-20', 22],
 ['CLE', 'SEA', '2016-04-21', 10],
 ['SF', 'ARI', '2016-04-21', 13],
 ['CHW', 'LAA', '2016-04-21', 25],
 ['KC', 'DET', '2016-04-21', 33],
 ['MIL', 'MIN', '2016-04-21', 19],
 ['SD', 'PIT', '2016-04-21', 1],
 ['MIA', 'WSH', '2016-04-21', 57],
 ['TEX', 'HOU', '2016-04-21', 21],
 ['NYY', 'OAK', '2016-04-21', 35],
 ['BAL', 'TOR', '2016-04-21', 22],
 ['ATL', 'LAD', '2016-04-21', 2],
 ['CIN', 'CHC', '2016-04-21', 64],
 ['BOS', 'TB', '2016-04-21', 50],
 ['HOU', 'BOS', '2016-04-22', 63],
 ['DET', 'CLE', '2016-04-22', 62],
 ['LAA', 'SEA', '2016-04-22', 28],
 ['COL', 'LAD', '2016-04-22', 44],
 ['SF', 'MIA', '2016-04-22', 13],
 ['KC', 'BAL', '2016-04-22', 33],
 ['WSH', 'MIN', '2016-04-22', 53],
 ['ARI', 'PIT', '2016-04-22', 54],
 ['ATL', 'NYM', '2016-04-22', 2],
 ['MIL', 'PHI', '2016-04-22', 19],
 ['CHW', 'TEX', '2016-04-22', 25],
 ['TOR', 'OAK', '2016-04-22', 42],
 ['CIN', 'CHC', '2016-04-22', 64],
 ['SD', 'STL', '2016-04-22', 1],
 ['NYY', 'TB', '2016-04-22', 35],
 ['HOU', 'BOS', '2016-04-23', 63],
 ['MIL', 'PHI', '2016-04-23', 19],
 ['COL', 'LAD', '2016-04-23', 44],
 ['ATL', 'NYM', '2016-04-23', 2],
 ['WSH', 'MIN', '2016-04-23', 53],
 ['SF', 'MIA', '2016-04-23', 13],
 ['ARI', 'PIT', '2016-04-23', 54],
 ['DET', 'CLE', '2016-04-23', 62],
 ['KC', 'BAL', '2016-04-23', 33],
 ['CIN', 'CHC', '2016-04-23', 64],
 ['LAA', 'SEA', '2016-04-23', 28],
 ['SD', 'STL', '2016-04-23', 1],
 ['NYY', 'TB', '2016-04-23', 35],
 ['TOR', 'OAK', '2016-04-23', 42],
 ['CHW', 'TEX', '2016-04-23', 25],
 ['CIN', 'CHC', '2016-04-24', 64],
 ['LAA', 'SEA', '2016-04-24', 28],
 ['WSH', 'MIN', '2016-04-24', 53],
 ['DET', 'CLE', '2016-04-24', 62],
 ['TOR', 'OAK', '2016-04-24', 42],
 ['ARI', 'PIT', '2016-04-24', 54],
 ['KC', 'BAL', '2016-04-24', 33],
 ['CHW', 'TEX', '2016-04-24', 25],
 ['SF', 'MIA', '2016-04-24', 13],
 ['MIL', 'PHI', '2016-04-24', 19],
 ['ATL', 'NYM', '2016-04-24', 2],
 ['NYY', 'TB', '2016-04-24', 35],
 ['SD', 'STL', '2016-04-24', 1],
 ['HOU', 'BOS', '2016-04-24', 63],
 ['COL', 'LAD', '2016-04-24', 44],
 ['ATL', 'BOS', '2016-04-25', 2],
 ['TB', 'BAL', '2016-04-25', 18],
 ['COL', 'PIT', '2016-04-25', 44],
 ['MIN', 'CLE', '2016-04-25', 14],
 ['TEX', 'NYY', '2016-04-25', 21],
 ['SF', 'SD', '2016-04-25', 13],
 ['LAA', 'KC', '2016-04-25', 28],
 ['DET', 'OAK', '2016-04-25', 62],
 ['TOR', 'CHW', '2016-04-25', 42],
 ['SEA', 'HOU', '2016-04-25', 65],
 ['ARI', 'STL', '2016-04-25', 54],
 ['NYM', 'CIN', '2016-04-25', 8],
 ['LAD', 'MIA', '2016-04-25', 31],
 ['LAA', 'KC', '2016-04-26', 28],
 ['LAD', 'MIA', '2016-04-26', 31],
 ['SF', 'SD', '2016-04-26', 13],
 ['SEA', 'HOU', '2016-04-26', 65],
 ['DET', 'OAK', '2016-04-26', 62],
 ['CHC', 'MIL', '2016-04-26', 27],
 ['MIN', 'CLE', '2016-04-26', 14],
 ['COL', 'PIT', '2016-04-26', 44],
 ['NYM', 'CIN', '2016-04-26', 8],
 ['TB', 'BAL', '2016-04-26', 18],
 ['WSH', 'PHI', '2016-04-26', 53],
 ['ARI', 'STL', '2016-04-26', 54],
 ['ATL', 'BOS', '2016-04-26', 2],
 ['TOR', 'CHW', '2016-04-26', 42],
 ['TEX', 'NYY', '2016-04-26', 21],
 ['CHC', 'MIL', '2016-04-27', 27],
 ['ARI', 'STL', '2016-04-27', 54],
 ['BOS', 'ATL', '2016-04-27', 50],
 ['TOR', 'CHW', '2016-04-27', 42],
 ['WSH', 'PHI', '2016-04-27', 53],
 ['NYM', 'CIN', '2016-04-27', 8],
 ['MIN', 'CLE', '2016-04-27', 14],
 ['DET', 'OAK', '2016-04-27', 62],
 ['LAD', 'MIA', '2016-04-27', 31],
 ['TEX', 'NYY', '2016-04-27', 21],
 ['SF', 'SD', '2016-04-27', 13],
 ['TB', 'BAL', '2016-04-27', 18],
 ['SEA', 'HOU', '2016-04-27', 65],
 ['LAA', 'KC', '2016-04-27', 28],
 ['COL', 'PIT', '2016-04-27', 44],
 ['BOS', 'ATL', '2016-04-28', 50],
 ['COL', 'PIT', '2016-04-28', 44],
 ['BAL', 'CHW', '2016-04-28', 22],
 ['CHC', 'MIL', '2016-04-28', 27],
 ['ARI', 'STL', '2016-04-28', 54],
 ['DET', 'OAK', '2016-04-28', 62],
 ['WSH', 'PHI', '2016-04-28', 53],
 ['LAD', 'MIA', '2016-04-28', 31],
 ['MIN', 'DET', '2016-04-29', 14],
 ['SEA', 'KC', '2016-04-29', 65],
 ['OAK', 'HOU', '2016-04-29', 23],
 ['LAD', 'SD', '2016-04-29', 31],
 ['TEX', 'LAA', '2016-04-29', 21],
 ['PIT', 'CIN', '2016-04-29', 29],
 ['STL', 'WSH', '2016-04-29', 41],
 ['PHI', 'CLE', '2016-04-29', 51],
 ['CHC', 'ATL', '2016-04-29', 27],
 ['ARI', 'COL', '2016-04-29', 54],
 ['BAL', 'CHW', '2016-04-29', 22],
 ['MIL', 'MIA', '2016-04-29', 19],
 ['BOS', 'NYY', '2016-04-29', 50],
 ['TB', 'TOR', '2016-04-29', 18],
 ['NYM', 'SF', '2016-04-29', 8],
 ['ARI', 'COL', '2016-04-30', 54],
 ['CHC', 'ATL', '2016-04-30', 27],
 ['MIL', 'MIA', '2016-04-30', 19],
 ['PHI', 'CLE', '2016-04-30', 51],
 ['BAL', 'CHW', '2016-04-30', 22],
 ['SEA', 'KC', '2016-04-30', 65],
 ['TEX', 'LAA', '2016-04-30', 21],
 ['PIT', 'CIN', '2016-04-30', 29],
 ['NYM', 'SF', '2016-04-30', 8],
 ['STL', 'WSH', '2016-04-30', 41],
 ['BOS', 'NYY', '2016-04-30', 50],
 ['MIN', 'DET', '2016-04-30', 14],
 ['TB', 'TOR', '2016-04-30', 18],
 ['LAD', 'SD', '2016-04-30', 31],
 ['OAK', 'HOU', '2016-04-30', 23],
 ['MIN', 'DET', '2016-05-01', 14],
 ['MIL', 'MIA', '2016-05-01', 19],
 ['BAL', 'CHW', '2016-05-01', 22],
 ['ARI', 'COL', '2016-05-01', 54],
 ['PHI', 'CLE', '2016-05-01', 51],
 ['CHC', 'ATL', '2016-05-01', 27],
 ['TB', 'TOR', '2016-05-01', 18],
 ['OAK', 'HOU', '2016-05-01', 23],
 ['BOS', 'NYY', '2016-05-01', 50],
 ['NYM', 'SF', '2016-05-01', 8],
 ['LAD', 'SD', '2016-05-01', 31],
 ['STL', 'WSH', '2016-05-01', 41],
 ['TEX', 'LAA', '2016-05-01', 21],
 ['PIT', 'CIN', '2016-05-01', 29],
 ['SEA', 'KC', '2016-05-01', 65],
 ['TOR', 'TEX', '2016-05-02', 42],
 ['STL', 'PHI', '2016-05-02', 41],
 ['NYM', 'ATL', '2016-05-02', 8],
 ['HOU', 'MIN', '2016-05-02', 63],
 ['MIL', 'LAA', '2016-05-02', 19],
 ['KC', 'WSH', '2016-05-02', 33],
 ['PIT', 'CHC', '2016-05-02', 29],
 ['OAK', 'SEA', '2016-05-02', 23],
 ['CIN', 'SF', '2016-05-02', 64],
 ['SD', 'COL', '2016-05-02', 1],
 ['MIL', 'LAA', '2016-05-03', 19],
 ['CLE', 'DET', '2016-05-03', 10],
 ['HOU', 'MIN', '2016-05-03', 63],
 ['NYM', 'ATL', '2016-05-03', 8],
 ['PIT', 'CHC', '2016-05-03', 29],
 ['MIA', 'ARI', '2016-05-03', 57],
 ['CHW', 'BOS', '2016-05-03', 25],
 ['SD', 'COL', '2016-05-03', 1],
 ['BAL', 'NYY', '2016-05-03', 22],
 ['CIN', 'SF', '2016-05-03', 64],
 ['TOR', 'TEX', '2016-05-03', 42],
 ['OAK', 'SEA', '2016-05-03', 23],
 ['KC', 'WSH', '2016-05-03', 33],
 ['STL', 'PHI', '2016-05-03', 41],
 ['TB', 'LAD', '2016-05-03', 18],
 ['NYM', 'ATL', '2016-05-04', 8],
 ['TB', 'LAD', '2016-05-04', 18],
 ['MIA', 'ARI', '2016-05-04', 57],
 ['HOU', 'MIN', '2016-05-04', 63],
 ['MIL', 'LAA', '2016-05-04', 19],
 ['CLE', 'DET', '2016-05-04', 10],
 ['KC', 'WSH', '2016-05-04', 33],
 ['PIT', 'CHC', '2016-05-04', 29],
 ['CIN', 'SF', '2016-05-04', 64],
 ['OAK', 'SEA', '2016-05-04', 23],
 ['STL', 'PHI', '2016-05-04', 41],
 ['CHW', 'BOS', '2016-05-04', 25],
 ['BAL', 'NYY', '2016-05-04', 22],
 ['TOR', 'TEX', '2016-05-04', 42],
 ['SD', 'COL', '2016-05-04', 1],
 ['HOU', 'SEA', '2016-05-05', 63],
 ['SD', 'NYM', '2016-05-05', 1],
 ['CIN', 'MIL', '2016-05-05', 64],
 ['MIA', 'ARI', '2016-05-05', 57],
 ['CHW', 'BOS', '2016-05-05', 25],
 ['STL', 'PHI', '2016-05-05', 41],
 ['CHC', 'WSH', '2016-05-05', 27],
 ['TOR', 'TEX', '2016-05-05', 42],
 ['SF', 'COL', '2016-05-05', 13],
 ['BAL', 'NYY', '2016-05-05', 22],
 ['CLE', 'DET', '2016-05-05', 10],
 ['SF', 'COL', '2016-05-06', 13],
 ['BAL', 'OAK', '2016-05-06', 22],
 ['NYY', 'BOS', '2016-05-06', 35],
 ['CHW', 'MIN', '2016-05-06', 25],
 ['CHC', 'WSH', '2016-05-06', 27],
 ['CLE', 'KC', '2016-05-06', 10],
 ['LAA', 'TB', '2016-05-06', 28],
 ['HOU', 'SEA', '2016-05-06', 63],
 ['STL', 'PIT', '2016-05-06', 41],
 ['MIA', 'PHI', '2016-05-06', 57],
 ['SD', 'NYM', '2016-05-06', 1],
 ['TOR', 'LAD', '2016-05-06', 42],
 ['DET', 'TEX', '2016-05-06', 62],
 ['CIN', 'MIL', '2016-05-06', 64],
 ['ATL', 'ARI', '2016-05-06', 2],
 ['SD', 'NYM', '2016-05-07', 1],
 ['LAA', 'TB', '2016-05-07', 28],
 ['NYY', 'BOS', '2016-05-07', 35],
 ['DET', 'TEX', '2016-05-07', 62],
 ['HOU', 'SEA', '2016-05-07', 63],
 ['CHW', 'MIN', '2016-05-07', 25],
 ['ATL', 'ARI', '2016-05-07', 2],
 ['BAL', 'OAK', '2016-05-07', 22],
 ['MIA', 'PHI', '2016-05-07', 57],
 ['STL', 'PIT', '2016-05-07', 41],
 ['CLE', 'KC', '2016-05-07', 10],
 ['CIN', 'MIL', '2016-05-07', 64],
 ['CHC', 'WSH', '2016-05-07', 27],
 ['SF', 'COL', '2016-05-07', 13],
 ['TOR', 'LAD', '2016-05-07', 42],
 ['BAL', 'OAK', '2016-05-07', 22],
 ['ATL', 'ARI', '2016-05-08', 2],
 ['SF', 'COL', '2016-05-08', 13],
 ['MIA', 'PHI', '2016-05-08', 57],
 ['LAA', 'TB', '2016-05-08', 28],
 ['CLE', 'KC', '2016-05-08', 10],
 ['BAL', 'OAK', '2016-05-08', 22],
 ['SD', 'NYM', '2016-05-08', 1],
 ['STL', 'PIT', '2016-05-08', 41],
 ['HOU', 'SEA', '2016-05-08', 63],
 ['CIN', 'MIL', '2016-05-08', 64],
 ['DET', 'TEX', '2016-05-08', 62],
 ['TOR', 'LAD', '2016-05-08', 42],
 ['CHC', 'WSH', '2016-05-08', 27],
 ['CHW', 'MIN', '2016-05-08', 25],
 ['NYY', 'BOS', '2016-05-08', 35],
 ['TEX', 'CHW', '2016-05-09', 21],
 ['MIA', 'MIL', '2016-05-09', 57],
 ['SEA', 'TB', '2016-05-09', 65],
 ['CIN', 'PIT', '2016-05-09', 64],
 ['COL', 'ARI', '2016-05-09', 44],
 ['HOU', 'CLE', '2016-05-09', 63],
 ['CHC', 'SD', '2016-05-09', 27],
 ['MIN', 'BAL', '2016-05-09', 14],
 ['WSH', 'DET', '2016-05-09', 53],
 ['NYY', 'KC', '2016-05-09', 35],
 ['SF', 'TOR', '2016-05-09', 13],
 ['BOS', 'OAK', '2016-05-09', 50],
 ['LAD', 'NYM', '2016-05-09', 31],
 ['CIN', 'PIT', '2016-05-10', 64],
 ['COL', 'ARI', '2016-05-10', 44],
 ['LAA', 'STL', '2016-05-10', 28],
 ['NYY', 'KC', '2016-05-10', 35],
 ['TEX', 'CHW', '2016-05-10', 21],
 ['LAD', 'NYM', '2016-05-10', 31],
 ['SF', 'TOR', '2016-05-10', 13],
 ['SEA', 'TB', '2016-05-10', 65],
 ['MIN', 'BAL', '2016-05-10', 14],
 ['ATL', 'PHI', '2016-05-10', 2],
 ['BOS', 'OAK', '2016-05-10', 50],
 ['MIA', 'MIL', '2016-05-10', 57],
 ['WSH', 'DET', '2016-05-10', 53],
 ['CHC', 'SD', '2016-05-10', 27],
 ['HOU', 'CLE', '2016-05-10', 63],
 ['LAA', 'STL', '2016-05-11', 28],
 ['MIN', 'BAL', '2016-05-11', 14],
 ['BOS', 'OAK', '2016-05-11', 50],
 ['TEX', 'CHW', '2016-05-11', 21],
 ['CHC', 'SD', '2016-05-11', 27],
 ['MIA', 'MIL', '2016-05-11', 57],
 ['ATL', 'PHI', '2016-05-11', 2],
 ['HOU', 'CLE', '2016-05-11', 63],
 ['SF', 'TOR', '2016-05-11', 13],
 ['WSH', 'DET', '2016-05-11', 53],
 ['CIN', 'PIT', '2016-05-11', 64],
 ['COL', 'ARI', '2016-05-11', 44],
 ['SEA', 'TB', '2016-05-11', 65],
 ['CHC', 'SD', '2016-05-11', 27],
 ['NYY', 'KC', '2016-05-11', 35],
 ['LAD', 'NYM', '2016-05-11', 31],
 ['ATL', 'PHI', '2016-05-12', 2],
 ['LAD', 'NYM', '2016-05-12', 31],
 ['MIL', 'SD', '2016-05-12', 19],
 ['LAA', 'STL', '2016-05-12', 28],
 ['ARI', 'SF', '2016-05-12', 54],
 ['BOS', 'HOU', '2016-05-12', 50],
 ['BAL', 'DET', '2016-05-12', 22],
 ['NYY', 'KC', '2016-05-12', 35],
 ['BAL', 'DET', '2016-05-13', 22],
 ['SEA', 'LAA', '2016-05-13', 65],
 ['COL', 'NYM', '2016-05-13', 44],
 ['CLE', 'MIN', '2016-05-13', 10],
 ['ARI', 'SF', '2016-05-13', 54],
 ['KC', 'ATL', '2016-05-13', 33],
 ['BOS', 'HOU', '2016-05-13', 50],
 ['MIL', 'SD', '2016-05-13', 19],
 ['CHC', 'PIT', '2016-05-13', 27],
 ['LAD', 'STL', '2016-05-13', 31],
 ['TB', 'OAK', '2016-05-13', 18],
 ['TEX', 'TOR', '2016-05-13', 21],
 ['PHI', 'CIN', '2016-05-13', 51],
 ['NYY', 'CHW', '2016-05-13', 35],
 ['WSH', 'MIA', '2016-05-13', 53],
 ['CLE', 'MIN', '2016-05-14', 10],
 ['TEX', 'TOR', '2016-05-14', 21],
 ['NYY', 'CHW', '2016-05-14', 35],
 ['ARI', 'SF', '2016-05-14', 54],
 ['KC', 'ATL', '2016-05-14', 33],
 ['SEA', 'LAA', '2016-05-14', 65],
 ['BAL', 'DET', '2016-05-14', 22],
 ['BOS', 'HOU', '2016-05-14', 50],
 ['COL', 'NYM', '2016-05-14', 44],
 ['WSH', 'MIA', '2016-05-14', 53],
 ['WSH', 'MIA', '2016-05-14', 53],
 ['LAD', 'STL', '2016-05-14', 31],
 ['CHC', 'PIT', '2016-05-14', 27],
 ['TB', 'OAK', '2016-05-14', 18],
 ['MIL', 'SD', '2016-05-14', 19],
 ['PHI', 'CIN', '2016-05-14', 51],
 ['BOS', 'HOU', '2016-05-15', 50],
 ['NYY', 'CHW', '2016-05-15', 35],
 ['LAD', 'STL', '2016-05-15', 31],
 ['COL', 'NYM', '2016-05-15', 44],
 ['ARI', 'SF', '2016-05-15', 54],
 ['BAL', 'DET', '2016-05-15', 22],
 ['CHC', 'PIT', '2016-05-15', 27],
 ['CLE', 'MIN', '2016-05-15', 10],
 ['TEX', 'TOR', '2016-05-15', 21],
 ['PHI', 'CIN', '2016-05-15', 51],
 ['KC', 'ATL', '2016-05-15', 33],
 ['TB', 'OAK', '2016-05-15', 18],
 ['SEA', 'LAA', '2016-05-15', 65],
 ['MIL', 'SD', '2016-05-15', 19],
 ['WSH', 'MIA', '2016-05-15', 53],
 ['KC', 'BOS', '2016-05-16', 33],
 ['CLE', 'CIN', '2016-05-16', 10],

In [40]:
ss=[]
for i in context:
    for j in context_2:
        if i[3]==j[0]:
            a=i[:-1]+j[1:]
            ss.append(a)
ss

[['KC', 'NYM', '2016-04-03', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['PIT', 'STL', '2016-04-03', 'PNC Park', 'Pittsburgh', 'PA'],
 ['TB', 'TOR', '2016-04-03', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['MIL', 'SF', '2016-04-04', 'Miller Park', 'Milwaukee', 'WI'],
 ['LAA', 'CHC', '2016-04-04', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['ARI', 'COL', '2016-04-04', 'Chase Field', 'Phoenix', 'AZ'],
 ['NYY', 'HOU', '2016-04-04', 'Yankee Stadium', 'New York', 'NY'],
 ['CLE', 'BOS', '2016-04-04', 'Progressive Field', 'Cleveland', 'OH'],
 ['CIN', 'PHI', '2016-04-04', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['BAL',
  'MIN',
  '2016-04-04',
  'Oriole Park at Camden Yards',
  'Baltimore',
  'MD'],
 ['TB', 'TOR', '2016-04-04', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['SD', 'LAD', '2016-04-04', 'PETCO Park', 'San Diego', 'CA'],
 ['TEX',
  'SEA',
  '2016-04-04',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['OAK', 'CHW', '2016-04-04', 'O.co Coliseum', 'Oakland', 'CA'],
 ['ATL', 'WSH', '2016-04-04', 'Turner Field', 'Atlanta', 'GA'],
 ['MIA', 'DET', '2016-04-05', 'Marlins Park', 'Miami', 'FL'],
 ['CLE', 'BOS', '2016-04-05', 'Progressive Field', 'Cleveland', 'OH'],
 ['ARI', 'COL', '2016-04-05', 'Chase Field', 'Phoenix', 'AZ'],
 ['LAA', 'CHC', '2016-04-05', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['SD', 'LAD', '2016-04-05', 'PETCO Park', 'San Diego', 'CA'],
 ['MIL', 'SF', '2016-04-05', 'Miller Park', 'Milwaukee', 'WI'],
 ['NYY', 'HOU', '2016-04-05', 'Yankee Stadium', 'New York', 'NY'],
 ['OAK', 'CHW', '2016-04-05', 'O.co Coliseum', 'Oakland', 'CA'],
 ['KC', 'NYM', '2016-04-05', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['PIT', 'STL', '2016-04-05', 'PNC Park', 'Pittsburgh', 'PA'],
 ['TB', 'TOR', '2016-04-05', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['TEX',
  'SEA',
  '2016-04-05',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['BAL',
  'MIN',
  '2016-04-06',
  'Oriole Park at Camden Yards',
  'Baltimore',
  'MD'],
 ['MIA', 'DET', '2016-04-06', 'Marlins Park', 'Miami', 'FL'],
 ['NYY', 'HOU', '2016-04-06', 'Yankee Stadium', 'New York', 'NY'],
 ['TB', 'TOR', '2016-04-06', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['PIT', 'STL', '2016-04-06', 'PNC Park', 'Pittsburgh', 'PA'],
 ['CLE', 'BOS', '2016-04-06', 'Progressive Field', 'Cleveland', 'OH'],
 ['ATL', 'WSH', '2016-04-06', 'Turner Field', 'Atlanta', 'GA'],
 ['ARI', 'COL', '2016-04-06', 'Chase Field', 'Phoenix', 'AZ'],
 ['TEX',
  'SEA',
  '2016-04-06',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['CIN', 'PHI', '2016-04-06', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['OAK', 'CHW', '2016-04-06', 'O.co Coliseum', 'Oakland', 'CA'],
 ['MIL', 'SF', '2016-04-06', 'Miller Park', 'Milwaukee', 'WI'],
 ['SD', 'LAD', '2016-04-06', 'PETCO Park', 'San Diego', 'CA'],
 ['ARI', 'CHC', '2016-04-07', 'Chase Field', 'Phoenix', 'AZ'],
 ['CLE', 'BOS', '2016-04-07', 'Progressive Field', 'Cleveland', 'OH'],
 ['SF', 'LAD', '2016-04-07', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['NYY', 'HOU', '2016-04-07', 'Yankee Stadium', 'New York', 'NY'],
 ['LAA', 'TEX', '2016-04-07', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['BAL',
  'MIN',
  '2016-04-07',
  'Oriole Park at Camden Yards',
  'Baltimore',
  'MD'],
 ['CIN', 'PHI', '2016-04-07', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['OAK', 'CHW', '2016-04-07', 'O.co Coliseum', 'Oakland', 'CA'],
 ['WSH', 'MIA', '2016-04-07', 'Nationals Park', 'Washington', 'DC'],
 ['SEA', 'OAK', '2016-04-08', 'Safeco Field', 'Seattle', 'WA'],
 ['MIL', 'HOU', '2016-04-08', 'Miller Park', 'Milwaukee', 'WI'],
 ['LAA', 'TEX', '2016-04-08', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['ARI', 'CHC', '2016-04-08', 'Chase Field', 'Phoenix', 'AZ'],
 ['CHW', 'CLE', '2016-04-08', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['CIN', 'PIT', '2016-04-08', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['COL', 'SD', '2016-04-08', 'Coors Field', 'Denver', 'CO'],
 ['TOR', 'BOS', '2016-04-08', 'Rogers Centre', 'Toronto', 'ON'],
 ['SF', 'LAD', '2016-04-08', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['DET', 'NYY', '2016-04-08', 'Comerica Park', 'Detroit', 'MI'],
 ['NYM', 'PHI', '2016-04-08', 'Citi Field', 'New York', 'NY'],
 ['ATL', 'STL', '2016-04-08', 'Turner Field', 'Atlanta', 'GA'],
 ['BAL', 'TB', '2016-04-08', 'Oriole Park at Camden Yards', 'Baltimore', 'MD'],
 ['KC', 'MIN', '2016-04-08', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['COL', 'SD', '2016-04-09', 'Coors Field', 'Denver', 'CO'],
 ['CHW', 'CLE', '2016-04-09', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['WSH', 'MIA', '2016-04-09', 'Nationals Park', 'Washington', 'DC'],
 ['BAL', 'TB', '2016-04-09', 'Oriole Park at Camden Yards', 'Baltimore', 'MD'],
 ['ATL', 'STL', '2016-04-09', 'Turner Field', 'Atlanta', 'GA'],
 ['LAA', 'TEX', '2016-04-09', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['ARI', 'CHC', '2016-04-09', 'Chase Field', 'Phoenix', 'AZ'],
 ['MIL', 'HOU', '2016-04-09', 'Miller Park', 'Milwaukee', 'WI'],
 ['KC', 'MIN', '2016-04-09', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['DET', 'NYY', '2016-04-09', 'Comerica Park', 'Detroit', 'MI'],
 ['NYM', 'PHI', '2016-04-09', 'Citi Field', 'New York', 'NY'],
 ['SEA', 'OAK', '2016-04-09', 'Safeco Field', 'Seattle', 'WA'],
 ['SF', 'LAD', '2016-04-09', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['CIN', 'PIT', '2016-04-09', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['TOR', 'BOS', '2016-04-09', 'Rogers Centre', 'Toronto', 'ON'],
 ['NYM', 'PHI', '2016-04-10', 'Citi Field', 'New York', 'NY'],
 ['KC', 'MIN', '2016-04-10', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['CIN', 'PIT', '2016-04-10', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['WSH', 'MIA', '2016-04-10', 'Nationals Park', 'Washington', 'DC'],
 ['MIL', 'HOU', '2016-04-10', 'Miller Park', 'Milwaukee', 'WI'],
 ['SF', 'LAD', '2016-04-10', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['COL', 'SD', '2016-04-10', 'Coors Field', 'Denver', 'CO'],
 ['TOR', 'BOS', '2016-04-10', 'Rogers Centre', 'Toronto', 'ON'],
 ['CHW', 'CLE', '2016-04-10', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['DET', 'NYY', '2016-04-10', 'Comerica Park', 'Detroit', 'MI'],
 ['ATL', 'STL', '2016-04-10', 'Turner Field', 'Atlanta', 'GA'],
 ['ARI', 'CHC', '2016-04-10', 'Chase Field', 'Phoenix', 'AZ'],
 ['LAA', 'TEX', '2016-04-10', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['SEA', 'OAK', '2016-04-10', 'Safeco Field', 'Seattle', 'WA'],
 ['BAL', 'TB', '2016-04-10', 'Oriole Park at Camden Yards', 'Baltimore', 'MD'],
 ['BOS', 'BAL', '2016-04-11', 'Fenway Park', 'Boston', 'MA'],
 ['WSH', 'ATL', '2016-04-11', 'Nationals Park', 'Washington', 'DC'],
 ['CHC', 'CIN', '2016-04-11', 'Wrigley Field', 'Chicago', 'IL'],
 ['DET', 'PIT', '2016-04-11', 'Comerica Park', 'Detroit', 'MI'],
 ['MIN', 'CHW', '2016-04-11', 'Target Field', 'Minneapolis', 'MN'],
 ['STL', 'MIL', '2016-04-11', 'Busch Stadium', 'St. Louis', 'MO'],
 ['SEA', 'TEX', '2016-04-11', 'Safeco Field', 'Seattle', 'WA'],
 ['HOU', 'KC', '2016-04-11', 'Minute Maid Park', 'Houston', 'TX'],
 ['OAK', 'LAA', '2016-04-11', 'O.co Coliseum', 'Oakland', 'CA'],
 ['PHI', 'SD', '2016-04-11', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['NYM', 'MIA', '2016-04-11', 'Citi Field', 'New York', 'NY'],
 ['NYM', 'MIA', '2016-04-12', 'Citi Field', 'New York', 'NY'],
 ['HOU', 'KC', '2016-04-12', 'Minute Maid Park', 'Houston', 'TX'],
 ['LAD', 'ARI', '2016-04-12', 'Dodger Stadium', 'Los Angeles', 'CA'],
 ['DET', 'PIT', '2016-04-12', 'Comerica Park', 'Detroit', 'MI'],
 ['TB', 'CLE', '2016-04-12', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['COL', 'SF', '2016-04-12', 'Coors Field', 'Denver', 'CO'],
 ['SEA', 'TEX', '2016-04-12', 'Safeco Field', 'Seattle', 'WA'],
 ['BOS', 'BAL', '2016-04-12', 'Fenway Park', 'Boston', 'MA'],
 ['WSH', 'ATL', '2016-04-12', 'Nationals Park', 'Washington', 'DC'],
 ['TOR', 'NYY', '2016-04-12', 'Rogers Centre', 'Toronto', 'ON'],
 ['OAK', 'LAA', '2016-04-12', 'O.co Coliseum', 'Oakland', 'CA'],
 ['PHI', 'SD', '2016-04-12', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['LAD', 'ARI', '2016-04-13', 'Dodger Stadium', 'Los Angeles', 'CA'],
 ['BOS', 'BAL', '2016-04-13', 'Fenway Park', 'Boston', 'MA'],
 ['OAK', 'LAA', '2016-04-13', 'O.co Coliseum', 'Oakland', 'CA'],
 ['CHC', 'CIN', '2016-04-13', 'Wrigley Field', 'Chicago', 'IL'],
 ['PIT', 'DET', '2016-04-13', 'PNC Park', 'Pittsburgh', 'PA'],
 ['MIN', 'CHW', '2016-04-13', 'Target Field', 'Minneapolis', 'MN'],
 ['SEA', 'TEX', '2016-04-13', 'Safeco Field', 'Seattle', 'WA'],
 ['HOU', 'KC', '2016-04-13', 'Minute Maid Park', 'Houston', 'TX'],
 ['TOR', 'NYY', '2016-04-13', 'Rogers Centre', 'Toronto', 'ON'],
 ['COL', 'SF', '2016-04-13', 'Coors Field', 'Denver', 'CO'],
 ['TB', 'CLE', '2016-04-13', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['STL', 'MIL', '2016-04-13', 'Busch Stadium', 'St. Louis', 'MO'],
 ['NYM', 'MIA', '2016-04-13', 'Citi Field', 'New York', 'NY'],
 ['WSH', 'ATL', '2016-04-13', 'Nationals Park', 'Washington', 'DC'],
 ['PHI', 'SD', '2016-04-13', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['MIN', 'CHW', '2016-04-14', 'Target Field', 'Minneapolis', 'MN'],
 ['STL', 'MIL', '2016-04-14', 'Busch Stadium', 'St. Louis', 'MO'],
 ['WSH', 'ATL', '2016-04-14', 'Nationals Park', 'Washington', 'DC'],
 ['TEX',
  'BAL',
  '2016-04-14',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['LAD', 'ARI', '2016-04-14', 'Dodger Stadium', 'Los Angeles', 'CA'],
 ['CHC', 'CIN', '2016-04-14', 'Wrigley Field', 'Chicago', 'IL'],
 ['HOU', 'KC', '2016-04-14', 'Minute Maid Park', 'Houston', 'TX'],
 ['TB', 'CLE', '2016-04-14', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['COL', 'SF', '2016-04-14', 'Coors Field', 'Denver', 'CO'],
 ['TOR', 'NYY', '2016-04-14', 'Rogers Centre', 'Toronto', 'ON'],
 ['PHI', 'SD', '2016-04-14', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['PIT', 'DET', '2016-04-14', 'PNC Park', 'Pittsburgh', 'PA'],
 ['PHI', 'WSH', '2016-04-15', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['MIA', 'ATL', '2016-04-15', 'Marlins Park', 'Miami', 'FL'],
 ['HOU', 'DET', '2016-04-15', 'Minute Maid Park', 'Houston', 'TX'],
 ['MIN', 'LAA', '2016-04-15', 'Target Field', 'Minneapolis', 'MN'],
 ['PIT', 'MIL', '2016-04-15', 'PNC Park', 'Pittsburgh', 'PA'],
 ['OAK', 'KC', '2016-04-15', 'O.co Coliseum', 'Oakland', 'CA'],
 ['LAD', 'SF', '2016-04-15', 'Dodger Stadium', 'Los Angeles', 'CA'],
 ['SD', 'ARI', '2016-04-15', 'PETCO Park', 'San Diego', 'CA'],
 ['TEX',
  'BAL',
  '2016-04-15',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['TB', 'CHW', '2016-04-15', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['BOS', 'TOR', '2016-04-15', 'Fenway Park', 'Boston', 'MA'],
 ['CHC', 'COL', '2016-04-15', 'Wrigley Field', 'Chicago', 'IL'],
 ['CLE', 'NYM', '2016-04-15', 'Progressive Field', 'Cleveland', 'OH'],
 ['NYY', 'SEA', '2016-04-15', 'Yankee Stadium', 'New York', 'NY'],
 ['STL', 'CIN', '2016-04-15', 'Busch Stadium', 'St. Louis', 'MO'],
 ['MIN', 'LAA', '2016-04-16', 'Target Field', 'Minneapolis', 'MN'],
 ['HOU', 'DET', '2016-04-16', 'Minute Maid Park', 'Houston', 'TX'],
 ['CLE', 'NYM', '2016-04-16', 'Progressive Field', 'Cleveland', 'OH'],
 ['MIA', 'ATL', '2016-04-16', 'Marlins Park', 'Miami', 'FL'],
 ['PIT', 'MIL', '2016-04-16', 'PNC Park', 'Pittsburgh', 'PA'],
 ['SD', 'ARI', '2016-04-16', 'PETCO Park', 'San Diego', 'CA'],
 ['TEX',
  'BAL',
  '2016-04-16',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['TB', 'CHW', '2016-04-16', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['CHC', 'COL', '2016-04-16', 'Wrigley Field', 'Chicago', 'IL'],
 ['PHI', 'WSH', '2016-04-16', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['BOS', 'TOR', '2016-04-16', 'Fenway Park', 'Boston', 'MA'],
 ['STL', 'CIN', '2016-04-16', 'Busch Stadium', 'St. Louis', 'MO'],
 ['OAK', 'KC', '2016-04-16', 'O.co Coliseum', 'Oakland', 'CA'],
 ['NYY', 'SEA', '2016-04-16', 'Yankee Stadium', 'New York', 'NY'],
 ['LAD', 'SF', '2016-04-16', 'Dodger Stadium', 'Los Angeles', 'CA'],
 ['CLE', 'NYM', '2016-04-17', 'Progressive Field', 'Cleveland', 'OH'],
 ['MIA', 'ATL', '2016-04-17', 'Marlins Park', 'Miami', 'FL'],
 ['CHC', 'COL', '2016-04-17', 'Wrigley Field', 'Chicago', 'IL'],
 ['TB', 'CHW', '2016-04-17', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['LAD', 'SF', '2016-04-17', 'Dodger Stadium', 'Los Angeles', 'CA'],
 ['BOS', 'TOR', '2016-04-17', 'Fenway Park', 'Boston', 'MA'],
 ['TEX',
  'BAL',
  '2016-04-17',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['OAK', 'KC', '2016-04-17', 'O.co Coliseum', 'Oakland', 'CA'],
 ['HOU', 'DET', '2016-04-17', 'Minute Maid Park', 'Houston', 'TX'],
 ['MIN', 'LAA', '2016-04-17', 'Target Field', 'Minneapolis', 'MN'],
 ['SD', 'ARI', '2016-04-17', 'PETCO Park', 'San Diego', 'CA'],
 ['PHI', 'WSH', '2016-04-17', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['NYY', 'SEA', '2016-04-17', 'Yankee Stadium', 'New York', 'NY'],
 ['STL', 'CIN', '2016-04-17', 'Busch Stadium', 'St. Louis', 'MO'],
 ['PIT', 'MIL', '2016-04-17', 'PNC Park', 'Pittsburgh', 'PA'],
 ['MIN', 'MIL', '2016-04-18', 'Target Field', 'Minneapolis', 'MN'],
 ['BOS', 'TOR', '2016-04-18', 'Fenway Park', 'Boston', 'MA'],
 ['STL', 'CHC', '2016-04-18', 'Busch Stadium', 'St. Louis', 'MO'],
 ['PHI', 'NYM', '2016-04-18', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['CHW', 'LAA', '2016-04-18', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['CIN', 'COL', '2016-04-18', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['MIA', 'WSH', '2016-04-18', 'Marlins Park', 'Miami', 'FL'],
 ['SF', 'ARI', '2016-04-18', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['CIN', 'COL', '2016-04-19', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['CLE', 'SEA', '2016-04-19', 'Progressive Field', 'Cleveland', 'OH'],
 ['BAL',
  'TOR',
  '2016-04-19',
  'Oriole Park at Camden Yards',
  'Baltimore',
  'MD'],
 ['BOS', 'TB', '2016-04-19', 'Fenway Park', 'Boston', 'MA'],
 ['ATL', 'LAD', '2016-04-19', 'Turner Field', 'Atlanta', 'GA'],
 ['CHW', 'LAA', '2016-04-19', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['KC', 'DET', '2016-04-19', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['TEX',
  'HOU',
  '2016-04-19',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['SF', 'ARI', '2016-04-19', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['STL', 'CHC', '2016-04-19', 'Busch Stadium', 'St. Louis', 'MO'],
 ['MIN', 'MIL', '2016-04-19', 'Target Field', 'Minneapolis', 'MN'],
 ['SD', 'PIT', '2016-04-19', 'PETCO Park', 'San Diego', 'CA'],
 ['MIA', 'WSH', '2016-04-19', 'Marlins Park', 'Miami', 'FL'],
 ['PHI', 'NYM', '2016-04-19', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['NYY', 'OAK', '2016-04-19', 'Yankee Stadium', 'New York', 'NY'],
 ['CHW', 'LAA', '2016-04-20', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['MIL', 'MIN', '2016-04-20', 'Miller Park', 'Milwaukee', 'WI'],
 ['MIA', 'WSH', '2016-04-20', 'Marlins Park', 'Miami', 'FL'],
 ['ATL', 'LAD', '2016-04-20', 'Turner Field', 'Atlanta', 'GA'],
 ['CLE', 'SEA', '2016-04-20', 'Progressive Field', 'Cleveland', 'OH'],
 ['CIN', 'COL', '2016-04-20', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['STL', 'CHC', '2016-04-20', 'Busch Stadium', 'St. Louis', 'MO'],
 ['TEX',
  'HOU',
  '2016-04-20',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['SD', 'PIT', '2016-04-20', 'PETCO Park', 'San Diego', 'CA'],
 ['KC', 'DET', '2016-04-20', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['NYY', 'OAK', '2016-04-20', 'Yankee Stadium', 'New York', 'NY'],
 ['PHI', 'NYM', '2016-04-20', 'Citizens Bank Park', 'Philadelphia', 'PA'],
 ['BOS', 'TB', '2016-04-20', 'Fenway Park', 'Boston', 'MA'],
 ['SF', 'ARI', '2016-04-20', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['BAL',
  'TOR',
  '2016-04-20',
  'Oriole Park at Camden Yards',
  'Baltimore',
  'MD'],
 ['CLE', 'SEA', '2016-04-21', 'Progressive Field', 'Cleveland', 'OH'],
 ['SF', 'ARI', '2016-04-21', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['CHW', 'LAA', '2016-04-21', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['KC', 'DET', '2016-04-21', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['MIL', 'MIN', '2016-04-21', 'Miller Park', 'Milwaukee', 'WI'],
 ['SD', 'PIT', '2016-04-21', 'PETCO Park', 'San Diego', 'CA'],
 ['MIA', 'WSH', '2016-04-21', 'Marlins Park', 'Miami', 'FL'],
 ['TEX',
  'HOU',
  '2016-04-21',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],
 ['NYY', 'OAK', '2016-04-21', 'Yankee Stadium', 'New York', 'NY'],
 ['BAL',
  'TOR',
  '2016-04-21',
  'Oriole Park at Camden Yards',
  'Baltimore',
  'MD'],
 ['ATL', 'LAD', '2016-04-21', 'Turner Field', 'Atlanta', 'GA'],
 ['CIN', 'CHC', '2016-04-21', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['BOS', 'TB', '2016-04-21', 'Fenway Park', 'Boston', 'MA'],
 ['HOU', 'BOS', '2016-04-22', 'Minute Maid Park', 'Houston', 'TX'],
 ['DET', 'CLE', '2016-04-22', 'Comerica Park', 'Detroit', 'MI'],
 ['LAA', 'SEA', '2016-04-22', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['COL', 'LAD', '2016-04-22', 'Coors Field', 'Denver', 'CO'],
 ['SF', 'MIA', '2016-04-22', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['KC', 'BAL', '2016-04-22', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['WSH', 'MIN', '2016-04-22', 'Nationals Park', 'Washington', 'DC'],
 ['ARI', 'PIT', '2016-04-22', 'Chase Field', 'Phoenix', 'AZ'],
 ['ATL', 'NYM', '2016-04-22', 'Turner Field', 'Atlanta', 'GA'],
 ['MIL', 'PHI', '2016-04-22', 'Miller Park', 'Milwaukee', 'WI'],
 ['CHW', 'TEX', '2016-04-22', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['TOR', 'OAK', '2016-04-22', 'Rogers Centre', 'Toronto', 'ON'],
 ['CIN', 'CHC', '2016-04-22', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['SD', 'STL', '2016-04-22', 'PETCO Park', 'San Diego', 'CA'],
 ['NYY', 'TB', '2016-04-22', 'Yankee Stadium', 'New York', 'NY'],
 ['HOU', 'BOS', '2016-04-23', 'Minute Maid Park', 'Houston', 'TX'],
 ['MIL', 'PHI', '2016-04-23', 'Miller Park', 'Milwaukee', 'WI'],
 ['COL', 'LAD', '2016-04-23', 'Coors Field', 'Denver', 'CO'],
 ['ATL', 'NYM', '2016-04-23', 'Turner Field', 'Atlanta', 'GA'],
 ['WSH', 'MIN', '2016-04-23', 'Nationals Park', 'Washington', 'DC'],
 ['SF', 'MIA', '2016-04-23', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['ARI', 'PIT', '2016-04-23', 'Chase Field', 'Phoenix', 'AZ'],
 ['DET', 'CLE', '2016-04-23', 'Comerica Park', 'Detroit', 'MI'],
 ['KC', 'BAL', '2016-04-23', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['CIN', 'CHC', '2016-04-23', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['LAA', 'SEA', '2016-04-23', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['SD', 'STL', '2016-04-23', 'PETCO Park', 'San Diego', 'CA'],
 ['NYY', 'TB', '2016-04-23', 'Yankee Stadium', 'New York', 'NY'],
 ['TOR', 'OAK', '2016-04-23', 'Rogers Centre', 'Toronto', 'ON'],
 ['CHW', 'TEX', '2016-04-23', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['CIN', 'CHC', '2016-04-24', 'Great American Ball Park', 'Cincinnati', 'OH'],
 ['LAA', 'SEA', '2016-04-24', 'Angel Stadium of Anaheim', 'Anaheim', 'CA'],
 ['WSH', 'MIN', '2016-04-24', 'Nationals Park', 'Washington', 'DC'],
 ['DET', 'CLE', '2016-04-24', 'Comerica Park', 'Detroit', 'MI'],
 ['TOR', 'OAK', '2016-04-24', 'Rogers Centre', 'Toronto', 'ON'],
 ['ARI', 'PIT', '2016-04-24', 'Chase Field', 'Phoenix', 'AZ'],
 ['KC', 'BAL', '2016-04-24', 'Kauffman Stadium', 'Kansas City', 'MO'],
 ['CHW', 'TEX', '2016-04-24', 'U.S. Cellular Field', 'Chicago', 'IL'],
 ['SF', 'MIA', '2016-04-24', 'AT&amp;T Park', 'San Francisco', 'CA'],
 ['MIL', 'PHI', '2016-04-24', 'Miller Park', 'Milwaukee', 'WI'],
 ['ATL', 'NYM', '2016-04-24', 'Turner Field', 'Atlanta', 'GA'],
 ['NYY', 'TB', '2016-04-24', 'Yankee Stadium', 'New York', 'NY'],
 ['SD', 'STL', '2016-04-24', 'PETCO Park', 'San Diego', 'CA'],
 ['HOU', 'BOS', '2016-04-24', 'Minute Maid Park', 'Houston', 'TX'],
 ['COL', 'LAD', '2016-04-24', 'Coors Field', 'Denver', 'CO'],
 ['ATL', 'BOS', '2016-04-25', 'Turner Field', 'Atlanta', 'GA'],
 ['TB', 'BAL', '2016-04-25', 'Tropicana Field', 'St. Petersburg', 'FL'],
 ['COL', 'PIT', '2016-04-25', 'Coors Field', 'Denver', 'CO'],
 ['MIN', 'CLE', '2016-04-25', 'Target Field', 'Minneapolis', 'MN'],
 ['TEX',
  'NYY',
  '2016-04-25',
  'Globe Life Park in Arlington',
  'Arlington',
  'TX'],

In [41]:
final = []
for a in ss:
    if 'HOU' in a:
        #print(a)
        final.append(a)
    else:
        pass

In [44]:
df_q6=pd.DataFrame(columns=['Home Team','Away team','Day', 'Stadium','City','State'])
for i in range(164):
    df_q6.loc[i]= final[i]
df_q6

,Home Team,Away team,Day,Stadium,City,State
0,NYY,HOU,2016-04-04,Yankee Stadium,New York,NY
1,NYY,HOU,2016-04-05,Yankee Stadium,New York,NY
2,NYY,HOU,2016-04-06,Yankee Stadium,New York,NY
3,NYY,HOU,2016-04-07,Yankee Stadium,New York,NY
4,MIL,HOU,2016-04-08,Miller Park,Milwaukee,WI
5,MIL,HOU,2016-04-09,Miller Park,Milwaukee,WI
6,MIL,HOU,2016-04-10,Miller Park,Milwaukee,WI
7,HOU,KC,2016-04-11,Minute Maid Park,Houston,TX
8,HOU,KC,2016-04-12,Minute Maid Park,Houston,TX
9,HOU,KC,2016-04-13,Minute Maid Park,Houston,TX
10,HOU,KC,2016-04-14,Minute Maid Park,Houston,TX
11,HOU,DET,2016-04-15,Minute Maid Park,Houston,TX
12,HOU,DET,2016-04-16,Minute Maid Park,Houston,TX
13,HOU,DET,2016-04-17,Minute Maid Park,Houston,TX
14,TEX,HOU,2016-04-19,Globe Life Park in Arlington,Arlington,TX
15,TEX,HOU,2016-04-20,Globe Life Park in Arlington,Arlington,TX
16,TEX,HOU,2016-04-21,Globe Life Park in Arlington,Arlington,TX
17,HOU,BOS,2016-04-22,Minute Maid Park,Houston,TX
18,HOU,BOS,2016-04-23,Minute Maid Park,Houston,TX
19,HOU,BOS,2016-04-24,Minute Maid Park,Houston,TX
20,SEA,HOU,2016-04-25,Safeco Field,Seattle,WA
21,SEA,HOU,2016-04-26,Safeco Field,Seattle,WA
22,SEA,HOU,2016-04-27,Safeco Field,Seattle,WA
23,OAK,HOU,2016-04-29,O.co Coliseum,Oakland,CA
24,OAK,HOU,2016-04-30,O.co Coliseum,Oakland,CA
25,OAK,HOU,2016-05-01,O.co Coliseum,Oakland,CA
26,HOU,MIN,2016-05-02,Minute Maid Park,Houston,TX
27,HOU,MIN,2016-05-03,Minute Maid Park,Houston,TX
28,HOU,MIN,2016-05-04,Minute Maid Park,Houston,TX
29,HOU,SEA,2016-05-05,Minute Maid Park,Houston,TX
...,...,...,...,...,...,...
134,HOU,OAK,2016-08-31,Minute Maid Park,Houston,TX
135,TEX,HOU,2016-09-02,Globe Life Park in Arlington,Arlington,TX
136,TEX,HOU,2016-09-03,Globe Life Park in Arlington,Arlington,TX
137,TEX,HOU,2016-09-04,Globe Life Park in Arlington,Arlington,TX
138,CLE,HOU,2016-09-05,Progressive Field,Cleveland,OH
139,CLE,HOU,2016-09-06,Progressive Field,Cleveland,OH
140,CLE,HOU,2016-09-07,Progressive Field,Cleveland,OH
141,CLE,HOU,2016-09-08,Progressive Field,Cleveland,OH
142,HOU,CHC,2016-09-09,Minute Maid Park,Houston,TX
143,HOU,CHC,2016-09-10,Minute Maid Park,Houston,TX
144,HOU,CHC,2016-09-11,Minute Maid Park,Houston,TX
145,HOU,TEX,2016-09-12,Minute Maid Park,Houston,TX
146,HOU,TEX,2016-09-13,Minute Maid Park,Houston,TX
147,HOU,TEX,2016-09-14,Minute Maid Park,Houston,TX
148,SEA,HOU,2016-09-16,Safeco Field,Seattle,WA
149,SEA,HOU,2016-09-17,Safeco Field,Seattle,WA
150,SEA,HOU,2016-09-18,Safeco Field,Seattle,WA
151,OAK,HOU,2016-09-19,O.co Coliseum,Oakland,CA
152,OAK,HOU,2016-09-20,O.co Coliseum,Oakland,CA
153,OAK,HOU,2016-09-21,O.co Coliseum,Oakland,CA
154,HOU,LAA,2016-09-22,Minute Maid Park,Houston,TX
155,HOU,LAA,2016-09-23,Minute Maid Park,Houston,TX
156,HOU,LAA,2016-09-24,Minute Maid Park,Houston,TX
157,HOU,LAA,2016-09-25,Minute Maid Park,Houston,TX
158,HOU,SEA,2016-09-26,Minute Maid Park,Houston,TX
159,HOU,SEA,2016-09-27,Minute Maid Park,Houston,TX
160,HOU,SEA,2016-09-28,Minute Maid Park,Houston,TX
161,LAA,HOU,2016-09-30,Angel Stadium of Anaheim,Anaheim,CA
162,LAA,HOU,2016-10-01,Angel Stadium of Anaheim,Anaheim,CA
163,LAA,HOU,2016-10-02,Angel Stadium of Anaheim,Anaheim,CA

In [45]:
df_q6.to_csv('/Users/richard/Desktop/660D Web Analytics/q6.csv')